api/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from api.views import VersaoAPIView

app_name = 'api'

urlpatterns = [
    path('versao/', VersaoAPIView.as_view(), name='versao'),
    path('auth/', include('api.urls_auth')),
    path('docs/', include('api.urls_docs')),

    path('instituicao/', include('instituicao.urls_api')),
    path('painel/', include('painel.urls_api')),
    path('professor/', include('professor.urls_api')),
    path('situacao/', include('situacao.urls_api')),
    path('tarefa/', include('tarefa.urls_api')),

]

cata/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('api/', include("api.urls")),


    path('aluno/', include('aluno.urls')),
    path('professor/', include('professor.urls')),
    path('instituicao/', include('instituicao.urls')),
    path('situacao/', include('situacao.urls')),
    path('tarefa/', include('tarefa.urls')),
    path('', include('painel.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#path('cata/tarefa/', include('tarefa.urls')),

professor/urls.py
from django.urls import path

from . import views

app_name = "professor"

urlpatterns = [
    path("acoes/", views.acoes, name = "acoes"),
    path("conhecimento/", views.conhecimento, name = "conhecimento"),
    path("indice/", views.indice, name = "indice"),
    path("notas/", views.notas, name = "notas"),
    path("alunotarefas/<uuid:idturma>/<uuid:idaluno>", views.alunotarefas, name = "alunotarefas"),
    path("ementa/", views.ementa, name = "ementa"),
    path("ementaeditar/<uuid:id>", views.ementaeditar, name = "ementaeditar"),
]

situacao/urls.py
from django.urls import path

from . import views

app_name = "situacao"

#path("indicenovo/", views.indicenovo, name = "indicenovo"),
urlpatterns = [
    path("indiceitem/<uuid:id>", views.indiceitem, name = "indiceitem"),
    path("indicesubitem/<uuid:id>", views.indicesubitem, name = "indicesubitem"),
    path("indiceeditar/<uuid:id>", views.indiceeditar, name = "indiceeditar"),
    path("sobe/<uuid:id>", views.sobe, name = "sobe"),
    path("desce/<uuid:id>", views.desce, name = "desce"),
    path("problemanovo/<uuid:id>", views.problemanovo, name = "problemanovo"),
    path("problemaeditar/<uuid:id>", views.problemaeditar, name = "problemaeditar"),
    path("texto/<uuid:id>", views.texto, name = "texto"),
    path("simulacao/<uuid:id>", views.simulacao, name = "simulacao"),
    path("simulacaonovo/<uuid:id>", views.simulacaonovo, name = "simulacaonovo"),
    path("simulacaoapagar/<uuid:id>", views.simulacaoapagar, name = "simulacaoapagar"),
    path("simulacaoapagartodas/<uuid:id>", views.simulacaoapagartodas, name = "simulacaoapagartodas"),
    path("simulacaoimportar/<uuid:id>", views.simulacaoimportar, name = "simulacaoimportar"),
    path("vlraleatnovo/<uuid:id>", views.vlraleatnovo, name = "vlraleatnovo"),
    path("vlraleateditar/<uuid:id>", views.vlraleateditar, name = "vlraleateditar"),
    path("respostanovo/<uuid:id>", views.respostanovo, name = "respostanovo"),
    path("respostaeditar/<uuid:id>", views.respostaeditar, name = "respostaeditar"),
    path("textonovo/<uuid:id>", views.textonovo, name = "textonovo"),
    path("textoeditar/<uuid:id>", views.textoeditar, name = "textoeditar"),
    path("anexonovo/<uuid:id>", views.anexonovo, name = "anexonovo"),
    path("anexoeditar/<uuid:id>", views.anexoeditar, name = "anexoeditar"),
    path("apagar/<uuid:id>", views.apagar, name = "apagar"),
    path("programanovo/<uuid:id>", views.programanovo, name = "programanovo"),
    path("programaeditar/<uuid:id>", views.programaeditar, name = "programaeditar"),
    path("propostaeditar/<uuid:id>", views.propostaeditar, name = "propostaeditar"),
    path("proposta/<uuid:id>", views.proposta, name = "proposta"),
    path("testenovo/<uuid:id>", views.testenovo, name = "testenovo"),
    path("testeeditar/<uuid:id>", views.testeeditar, name = "testeeditar"),
]

painel/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser, UserManager

from painel.mixins import TimedModelMixin, UUIDModelMixin, UserModelMixin

class User(AbstractUser, UUIDModelMixin):
    CARGO=(('professor','Professor(a)'),('aluno','Aluno(a)'),('admin','Administrador(a)'),)

    # cargo
    cargo = models.CharField('Cargo',max_length=25,choices=CARGO)
    professor = models.ManyToManyField('self',symmetrical=False,related_name="professores",blank=True,default=None)

    objects = UserManager()

    class Meta:
        ordering = ["last_name"]
        verbose_name = "User"
        verbose_name_plural = "Users"

    def professores_mm(self):
        return " ".join(['*{} '.format(p.last_name) for p in self.professor.all()])

    def __concat_str__(self):
        if not self.professor.all():
            return self.last_name
        else:
            return self.professores_mm() + ' :-) ' + self.last_name

    def __str__(self):
        return self.__concat_str__()
        #return self.last_name



def variavel_arquivo(instance, filename):
    return "painel/variavel/arquivo/{}_{}".format(instance.id, filename)

class Variavel(UUIDModelMixin, TimedModelMixin, UserModelMixin):
    nome = models.CharField("Nome",max_length=100,help_text='Sem espaços, nem acentos. Tudo minúsculo.')
    valor = models.CharField("Valor",max_length=255,blank=True,default=None,null=True,help_text='...')
    texto = models.TextField("Texto",blank=True,default=None, null=True, help_text='...')
    arquivo = models.FileField("Arquivo",blank = True, default=None, null=True, upload_to = variavel_arquivo)

    class Meta:
        unique_together = ("usuario", "nome")
        verbose_name = "Variável"
        verbose_name_plural = "Variáveis"

    def __str__(self):
        return "{}".format(self.nome)

    def get_url(self):
        if self.arquivo is not None:
            return self.arquivo.url
        else:
            return "/arquivosemcaminho/"

situacao/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,render_to_response
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse
from datetime import date,timedelta,datetime,timezone

from situacao.models import Indice,Problema,Simulacao,ValorAleatorio,Resposta,Arquivo,Texto,Programa,Teste,Proposta
from situacao.forms import IndiceForm,Indice2Form,ProblemaForm,Problema2Form,ValorAleatorioForm,RespostaForm,TextoForm,ArquivoForm,ProgramaForm,Programa2Form,PropostaForm,TesteForm
from tarefa.models import Questao
'''
@login_required
def indicenovo(request):
    if request.method == 'POST':
        form=IndiceForm(request.user,request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('professor:indice'))
    else:
        form=IndiceForm(request.user)
    context = {'form':form}
    return render(request, 'situacao/indicenovo.html', context)
'''
@login_required
def indiceeditar(request,id):
    indice=Indice.objects.get(id=id)
    if request.method == 'POST':
        form=Indice2Form(request.POST,instance=indice)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('professor:indice'))
    else:
        form = Indice2Form(instance=indice)
    context = {'form':form,'indice':indice}
    return render(request, 'situacao/indiceeditar.html', context)


@login_required
def indiceitem(request,id):
    indice=Indice.objects.get(id=id)
    if request.method == 'POST':
        form=IndiceForm(request.POST)
        if form.is_valid():
            #form.save()
            novo=form.save(commit=False)
            novo.superior=indice.superior
            novo.conhecimento=indice.conhecimento
            novo.save()
            return HttpResponseRedirect(reverse('professor:indice'))
    else:
        #form = IndiceForm(initial={'superior': indice.superior,'conhecimento':indice.conhecimento})
        form = IndiceForm()
    context = {'form':form,'indice':indice}
    return render(request, 'situacao/indiceitem.html', context)

@login_required
def indicesubitem(request,id):
    indice=Indice.objects.get(id=id)
    if request.method == 'POST':
        form=IndiceForm(request.POST)
        if form.is_valid():
            #form.save()
            novo=form.save(commit=False)
            novo.superior=indice
            novo.conhecimento=indice.conhecimento
            novo.save()
            return HttpResponseRedirect(reverse('professor:indice'))
    else:
        #form = IndiceForm(initial={'superior': indice,'conhecimento':indice.conhecimento})
        form = IndiceForm()
    context = {'form':form,'indice':indice}
    return render(request, 'situacao/indicesubitem.html', context)


@login_required
def sobe(request,id):
    indice=Indice.objects.get(id=id)
    indice.subir_ordem()
    return HttpResponseRedirect(reverse('professor:indice'))

@login_required
def desce(request,id):
    indice=Indice.objects.get(id=id)
    indice.descer_ordem()
    return HttpResponseRedirect(reverse('professor:indice'))


@login_required
def problemanovo(request,id):
    indice=Indice.objects.get(id=id)
    if request.method == 'POST':
        form=ProblemaForm(request.POST,request.FILES)
        if form.is_valid():
            novo=form.save(commit=False)
            novo.usuario=request.user
            novo.save()
            novo.indices.add(indice)
            form.save_m2m()
            return HttpResponseRedirect(reverse('professor:indice'))
    else:
        form=ProblemaForm()
    context = {'form':form,'indice':indice}
    return render(request, 'situacao/problemanovo.html', context)

@login_required
def problemaeditar(request,id):
    problema=Problema.objects.get(id=id)
    if request.method == 'POST':
        form=Problema2Form(request.POST,request.FILES,instance=problema)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('professor:indice'))
    else:
        form = Problema2Form(instance=problema)
    context = {'form':form,'id':problema.id}
    return render(request, 'situacao/problemaeditar.html', context)

@login_required
def texto(request,id):
    texto=Texto.objects.get(id=id)
    context = {'texto':texto}
    return render(request, 'situacao/texto.html', context)

@login_required
def simulacao(request,id):
    usuario = request.user
    problema=Problema.objects.get(id=id,ativo=True)
    context = {'problema':problema}
    return render(request, 'situacao/simulacao.html', context)


@login_required
def simulacaonovo(request,id):
    problema=Problema.objects.get(id=id)
    Simulacao(problema=problema).save()
    return HttpResponseRedirect(reverse('situacao:simulacao',kwargs={'id': id}))

@login_required
def simulacaoapagar(request,id):
    simulacao=Simulacao.objects.get(id=id)
    Questao.objects.filter(problema=simulacao.problema).delete()
    simulacao.delete()
    return HttpResponseRedirect(reverse('situacao:simulacao',kwargs={'id': simulacao.problema.id}))


@login_required
def simulacaoapagartodas(request,id):
    Questao.objects.filter(problema__id=id).delete()
    Simulacao.objects.filter(problema__id=id).delete()
    return HttpResponseRedirect(reverse('situacao:simulacao',kwargs={'id': id}))



@login_required
def simulacaoimportar(request,id):
    if request.method == 'POST':
        simulacoes = request.POST.get('simulacoes')
        ## print(simulacoes)
        linhas=simulacoes.split('\n')
        for linha in linhas :
            if linha.strip() :
                ## print(linha)
                problema=Problema.objects.get(id=id)
                sim=Simulacao(problema=problema)
                sim.save()
                listadalinha=linha.strip().split('|')
                VA=listadalinha[0]
                if VA :
                    ## print('VA')
                    NVA=VA.strip().split(',')
                    for nva in NVA :
                        valor=nva.strip().split('=')
                        ## print("{}:{}".format(valor[0],valor[1]))
                        tbVA=ValorAleatorio(simulacao=sim,nome=valor[0],valor=valor[1]).save()

                R=listadalinha[1]
                if R :
                    ## print('R')
                    LR=R.strip().split(',')
                    for item in LR :
                        valor=item.strip().split('=')
                        ## print("{}:{}".format(valor[0],valor[1]))
                        tbR=Resposta(simulacao=sim,letra=valor[0],valor=valor[1]).save()

                A=listadalinha[2]
                if A :
                    ## print('A')
                    LA=A.strip().split(',')
                    for letra in LA :
                        ## print("{}".format(letra))
                        tbA=Arquivo(simulacao=sim,letra = letra).save()

                T=listadalinha[3]
                if T :
                    ## print('T')
                    LT=T.strip().split(',')
                    for letra in LT :
                        ## print("{}".format(letra))
                        tbT=Texto(simulacao=sim,letra = letra).save()

        return HttpResponseRedirect(reverse('situacao:simulacao',kwargs={'id': id}))
    context = {'id':id}
    return render(request, 'situacao/simulacaoimportar.html', context)

@login_required
def vlraleatnovo(request,id):
    if request.method == 'POST':
        form=ValorAleatorioForm(request.POST)
        if form.is_valid():
            novo=form.save(commit=False)
            simulacao=Simulacao.objects.get(id=id)
            novo.simulacao=simulacao
            novo.save()
            return HttpResponseRedirect(reverse('situacao:simulacao',kwargs={'id': simulacao.problema.id}))
    else:
        form=ValorAleatorioForm()
    context = {'form':form,'id':id}
    return render(request, 'situacao/vlraleatnovo.html', context)

@login_required
def vlraleateditar(request,id):
    va=ValorAleatorio.objects.get(id=id)
    if request.method == 'POST':
        form=ValorAleatorioForm(request.POST,instance=va)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('situacao:simulacao',kwargs={'id': va.simulacao.problema.id}))
    else:
        form = ValorAleatorioForm(instance=va)
    context = {'form':form,'id':id}
    return render(request, 'situacao/vlraleateditar.html', context)


@login_required
def respostanovo(request,id):
    if request.method == 'POST':
        form=RespostaForm(request.POST)
        if form.is_valid():
            novo=form.save(commit=False)
            simulacao=Simulacao.objects.get(id=id)
            novo.simulacao=simulacao
            novo.save()
            return HttpResponseRedirect(reverse('situacao:simulacao',kwargs={'id': simulacao.problema.id}))
    else:
        form=RespostaForm()
    context = {'form':form,'id':id}
    return render(request, 'situacao/respostanovo.html', context)

@login_required
def respostaeditar(request,id):
    resposta=Resposta.objects.get(id=id)
    if request.method == 'POST':
        form=RespostaForm(request.POST,instance=resposta)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('situacao:simulacao',kwargs={'id': resposta.simulacao.problema.id}))
    else:
        form = RespostaForm(instance=resposta)
    context = {'form':form,'id':id}
    return render(request, 'situacao/respostaeditar.html', context)


@login_required
def textonovo(request,id):
    if request.method == 'POST':
        form=TextoForm(request.POST)
        if form.is_valid():
            novo=form.save(commit=False)
            simulacao=Simulacao.objects.get(id=id)
            novo.simulacao=simulacao
            novo.save()
            return HttpResponseRedirect(reverse('situacao:simulacao',kwargs={'id': simulacao.problema.id}))
    else:
        form=TextoForm()

situacao/templates/situacao/anexoeditar.html
{%extends 'base.html' %}

{%load static from staticfiles %}

{% block titulo%}
    CAT@::Ações Prof
{%endblock%}
{% block corpo%}

{% include 'cabecalho.html' %}

    {%if user.is_authenticated %}
        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-10 col-md-10">
                Olá {{user.get_cargo_display}} {{user.last_name}}. Hoje é {% now "d-m-Y H:i"%}.
                <small>
                  ( <a href="{% url 'professor:indice' %}"> Índice </a> )
                </small>
                <hr>
            </div>
            </div>
        </div> <!-- /container 1-->

        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-10 col-md-10">
                <h3>Editar este arquivo.</h3><small>Para apagar este item e todos ligados a ele clique nos três pontinhos <a href={% url 'situacao:apagar' id %}  title='Se clicar aqui todos os itens ligados a este serão apagados.'> ...</a></small></br></br>
                <form action="{% url 'situacao:anexoeditar' id %}" method="POST" enctype="multipart/form-data">{%csrf_token%}
                  {% include 'formvictor.html' with form=form %}
                    <input type="submit" value="Enviar informações" />
                </form>
            </div>
            </div>
        </div> <!-- /container 2-->



        {%else%}
            </br></br>Acesso não permitido. Favor procurar o Professor desta turma.
        {%endif%}

    {%endblock%}

situacao/templates/situacao/anexonovo.html
{%extends 'base.html' %}

{%load static from staticfiles %}

{% block titulo%}
    CAT@::Ações Prof
{%endblock%}
{% block corpo%}

{% include 'cabecalho.html' %}

    {%if user.is_authenticated %}
        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-10 col-md-10">
                Olá {{user.get_cargo_display}} {{user.last_name}}. Hoje é {% now "d-m-Y H:i"%}.
                <small>
                  ( <a href="{% url 'professor:indice' %}"> Índice </a> )
                </small>
                <hr>
            </div>
            </div>
        </div> <!-- /container 1-->

        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-10 col-md-10">
                <h3>Informe novo anexo.</h3>
                <form action="{% url 'situacao:anexonovo' id %}" method="POST" enctype="multipart/form-data">{%csrf_token%}
                  {% include 'formvictor.html' with form=form %}
                    <input type="submit" value="Enviar informações" />
                </form>
            </div>
            </div>
        </div> <!-- /container 2-->

        {%else%}
            </br></br>Acesso não permitido. Favor procurar o Professor desta turma.
        {%endif%}

    {%endblock%}

situacao/templates/situacao/indiceeditar.html
{%extends 'base.html' %}

{%load static from staticfiles %}

{% block titulo%}
    CAT@::Ações Prof
{%endblock%}
{% block corpo%}

{% include 'cabecalho.html' %}

    {%if user.is_authenticated %}
        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-10 col-md-10">
                Olá {{user.get_cargo_display}} {{user.last_name}}. Hoje é {% now "d-m-Y H:i"%}.
                <small>
                    ( <a href="{% url 'professor:indice' %}"> Índice </a> )
                </small>
                <hr>
            </div>
            </div>
        </div> <!-- /container 1-->

        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-10 col-md-10">
                <h3>Editar este indice.</h3><small>Para apagar este item e todos ligados a ele clique nos três pontinhos <a href={% url 'situacao:apagar' indice.id %}  title='Se clicar aqui todos os itens ligados a este serão apagados.'> ...</a></small></br></br>
                <form action="{% url 'situacao:indiceeditar' indice.id %}" method="POST" enctype="multipart/form-data">{%csrf_token%}
                  {% include 'formvictor.html' with form=form %}
                    <input type="submit" value="Enviar informações" />
                </form>
            </div>
            </div>
        </div> <!-- /container 2-->



        {%else%}
            </br></br>Acesso não permitido. Favor procurar o Professor desta turma.
        {%endif%}

    {%endblock%}

situacao/templates/situacao/indiceitem.html
{%extends 'base.html' %}

{%load static from staticfiles %}

{% block titulo%}
    CAT@::Ações Prof
{%endblock%}
{% block corpo%}

{% include 'cabecalho.html' %}

    {%if user.is_authenticated %}
        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-10 col-md-10">
                Olá {{user.get_cargo_display}} {{user.last_name}}. Hoje é {% now "d-m-Y H:i"%}.
                <small>
                    ( <a href="{% url 'professor:indice' %}"> Índice </a> )
                </small>
                <hr>
            </div>
            </div>
        </div> <!-- /container 1-->

        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-10 col-md-10">
                <h3>Criar item ao lado (irmão) deste:</h3><small>Para apagar este item e todos ligados a ele clique nos três pontinhos <a href={% url 'situacao:apagar' indice.id %}  title='Se clicar aqui todos os itens ligados a este serão apagados.'> ...</a></small></br></br>
                <form action="{% url 'situacao:indiceitem' indice.id %}" method="POST" enctype="multipart/form-data">{%csrf_token%}
                  {% include 'formvictor.html' with form=form %}
                    <input type="submit" value="Enviar informações" />
                </form>
            </div>
            </div>
        </div> <!-- /container 2-->



        {%else%}
            </br></br>Acesso não permitido. Favor procurar o Professor desta turma.
        {%endif%}

    {%endblock%}

situacao/templates/situacao/indicesubitem.html
{%extends 'base.html' %}

{%load static from staticfiles %}

{% block titulo%}
    CAT@::Ações Prof
{%endblock%}
{% block corpo%}

{% include 'cabecalho.html' %}

    {%if user.is_authenticated %}
        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-10 col-md-10">
                Olá {{user.get_cargo_display}} {{user.last_name}}. Hoje é {% now "d-m-Y H:i"%}.
                <small>
                    ( <a href="{% url 'professor:indice' %}"> Índice </a> )
                </small>
                <hr>
            </div>
            </div>
        </div> <!-- /container 1-->

        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-10 col-md-10">
                <h3>Criar item filho deste:</h3><small>Para apagar este item e todos ligados a ele clique nos três pontinhos <a href={% url 'situacao:apagar' indice.id %}  title='Se clicar aqui todos os itens ligados a este serão apagados.'> ...</a></small></br></br>
                <form action="{% url 'situacao:indicesubitem' indice.id %}" method="POST" enctype="multipart/form-data">{%csrf_token%}
                  {% include 'formvictor.html' with form=form %}
                    <input type="submit" value="Enviar informações" />
                </form>
            </div>
            </div>
        </div> <!-- /container 2-->



        {%else%}
            </br></br>Acesso não permitido. Favor procurar o Professor desta turma.
        {%endif%}

    {%endblock%}

situacao/templates/situacao/simulacao.html
{%extends 'base.html' %}

{%load static from staticfiles %}

{% block titulo%}
    CAT@::Ações Prof
{%endblock%}
{% block corpo%}

{% include 'cabecalho.html' %}

    {%if user.is_authenticated %}
        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-10 col-md-10">
                Olá {{user.get_cargo_display}} {{user.last_name}}. Hoje é {% now "d-m-Y H:i"%}.
                <small>
                  ( <a href="{% url 'professor:indice' %}"> Índice </a> )
                </small>
                <hr>
            </div>
            </div>
        </div> <!-- /container 2-->


        <!-- Gerenciar Índices e Situações -->
        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-10 col-md-10">
              <h3>Simulações do problema: </h3>
              <h4>{{problema.referencia}} > {{problema.descricao}}</h4>
                <div class="dtree">
                   <small><a href="javascript: e.openAll();">Expandir tudo</a> | <a href="javascript: e.closeAll();">Contrair tudo</a></small>
                   <script type="text/javascript">
                    e = new dTree('e');
                            e.add(0,-1,'{{problema.referencia}}: {{problema.descricao}}');
                            // e.add("{{problema.id}}_id","0","Problema id: {{problema.id}}");
                            // e.add("{{problema.id}}_descricao","0","Descrição: {{problema.descricao}}");
                            e.add("{{problema.id}}_ativo","0","Ativo: {{problema.ativo}}");
                            e.add("{{problema.id}}_ver","0","Ver: <a href='/cata/media/{{problema.pdf}}'  title='Clique para ver pdf da questão'>  <i class='fas fa-eye'></i></a>");
                            e.add("{{problema.id}}_simulacoes","0","Simulações: {{problema.simulacoes.count}} |  <a href={% url 'situacao:simulacaoapagartodas' problema.id %} title='Apagar todas as simulações desta situação. Não apague simulações de problemas já aplicados.'> <i class='far fa-trash-alt'></i> </a> | <a href={% url 'situacao:simulacaonovo' problema.id %} title='nova simulação para esta situacao'> <i class='fas fa-plus'></i></a> | <a href={% url 'situacao:simulacaoimportar' problema.id %} title='importar simulações de arquivo'> <i class='fas fa-download'></i></a>");
                            {% for simulacao in problema.simulacoes.all %}
                                e.add("{{simulacao.id}}","{{problema.id}}_simulacoes","{{simulacao.id}} : {{simulacao.editado_em|date:'d-m-Y H:i'}} |  <a href={% url 'situacao:simulacaoapagar' simulacao.id %} title='Clique para apagar esta simulação. Não apague simulações de problemas já aplicados.'> <i class='far fa-trash-alt'></i> </a> | <a href={% url 'situacao:vlraleatnovo' simulacao.id %} title='Clique para novo Valor Aleatório'> <i class='fas fa-sliders-h'></i></a> | <a href={% url 'situacao:respostanovo' simulacao.id %} title='Clique para nova Resposta'> <i class='fas fa-dollar-sign'></i></a> |  <a href={% url 'situacao:anexonovo' simulacao.id %} title='Clique para novo Arquivo'> <i class='fas fa-chart-line'></i></a> |  <a href={% url 'situacao:textonovo' simulacao.id %} title='Clique para novo Texto'> <i class='fas fa-book'></i></a>");
                                {% for valoraleatorio in simulacao.valores_aleatorios.all %}
                                    e.add("{{valoraleatorio.id}}","{{simulacao.id}}","Valor Aleatorio: {{valoraleatorio.nome}}={{valoraleatorio.valor}} <a href={% url 'situacao:vlraleateditar' valoraleatorio.id %} title='Clique para editar este Valor Aleatório'>  <i class='fas fa-pencil-alt'></i></a>");
                                {% endfor %}
                                {% for resposta in simulacao.respostas.all %}
                                    e.add("{{resposta.id}}","{{simulacao.id}}","Resposta: {{resposta.letra}}={{resposta.valor}} <a href={% url 'situacao:respostaeditar' resposta.id %} title='Clique para editar esta Resposta'> <i class='fas fa-pencil-alt'></i></a>");
                                {% endfor %}
                                {% for arquivo in simulacao.arquivos.all %}
                                    e.add("{{arquivo.id}}","{{simulacao.id}}","Arquivo: {{arquivo.letra}} {% if arquivo.arquivo %} <a href='/cata/media/{{arquivo.arquivo}}'  title='Clique para ver'> <i class='fas fa-eye'></i></a> {% endif %} | <a href={% url 'situacao:anexoeditar' arquivo.id %} title='Clique para editar este arquivo'>  <i class='fas fa-pencil-alt'></i></a>");
                                {% endfor %}
                                {% for texto in simulacao.textos.all %}
                                    e.add("{{texto.id}}","{{simulacao.id}}","Texto: {{texto.letra}} {% if texto.texto %} ... {% endif %}  <a href={% url 'situacao:textoeditar' texto.id %} title='Clique para editar este texto'>  <i class='fas fa-pencil-alt'></i></a>");
                                {% endfor %}
                            {% endfor %}

                    document.write(e);
                    </script>
                </div>
            </div>
            </div>
        </div> <!-- /container 2-->


    {%else%}
        </br></br>Acesso não permitido. Favor procurar o Professor desta turma.
    {%endif%}

{%endblock%}