aluno/urls.py
from django.urls import path

from . import views

app_name = "aluno"

urlpatterns = [
    path("atuais/", views.atuais, name = "atuais"),
    path("todas/", views.todas, name = "todas"),
    path("editar/<uuid:id>", views.editar, name = "editar"),
    path("editaralgoritmo/<uuid:id>", views.editaralgoritmo, name = "editaralgoritmo"),
    path("publica", views.publica, name = "publica"),
]

api/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from api.views import VersaoAPIView

app_name = 'api'

urlpatterns = [
    path('versao/', VersaoAPIView.as_view(), name='versao'),
    path('auth/', include('api.urls_auth')),
    path('docs/', include('api.urls_docs')),

    path('instituicao/', include('instituicao.urls_api')),
    path('painel/', include('painel.urls_api')),
    path('professor/', include('professor.urls_api')),
    path('situacao/', include('situacao.urls_api')),
    path('tarefa/', include('tarefa.urls_api')),

]

cata/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('api/', include("api.urls")),


    path('aluno/', include('aluno.urls')),
    path('professor/', include('professor.urls')),
    path('instituicao/', include('instituicao.urls')),
    path('situacao/', include('situacao.urls')),
    path('tarefa/', include('tarefa.urls')),
    path('', include('painel.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#path('cata/tarefa/', include('tarefa.urls')),

painel/urls.py
from django.urls import path

from . import views

app_name = "painel"

urlpatterns = [
    path("", views.index, name = "index"),
    path("sair/", views.sair, name = "sair"),
    path("alunonovo/<uuid:id>", views.alunonovo, name = "alunonovo"),
    path("alunoeditar/<uuid:id>", views.alunoeditar, name = "alunoeditar"),
    path("senhanova/", views.senhanova, name = "senhanova"),
    path("senhareset/<uuid:id>", views.senhareset, name = "senhareset"),
]

professor/urls.py
from django.urls import path

from . import views

app_name = "professor"

urlpatterns = [
    path("acoes/", views.acoes, name = "acoes"),
    path("conhecimento/", views.conhecimento, name = "conhecimento"),
    path("indice/", views.indice, name = "indice"),
    path("notas/", views.notas, name = "notas"),
    path("alunotarefas/<uuid:idturma>/<uuid:idaluno>", views.alunotarefas, name = "alunotarefas"),
    path("ementa/", views.ementa, name = "ementa"),
    path("ementaeditar/<uuid:id>", views.ementaeditar, name = "ementaeditar"),
]

aluno/models.py
from django.db import models

# Create your models here.

painel/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser, UserManager

from painel.mixins import TimedModelMixin, UUIDModelMixin, UserModelMixin

class User(AbstractUser, UUIDModelMixin):
    CARGO=(('professor','Professor(a)'),('aluno','Aluno(a)'),('admin','Administrador(a)'),)

    # cargo
    cargo = models.CharField('Cargo',max_length=25,choices=CARGO)
    professor = models.ManyToManyField('self',symmetrical=False,related_name="professores",blank=True,default=None)

    objects = UserManager()

    class Meta:
        ordering = ["last_name"]
        verbose_name = "User"
        verbose_name_plural = "Users"

    def professores_mm(self):
        return " ".join(['*{} '.format(p.last_name) for p in self.professor.all()])

    def __concat_str__(self):
        if not self.professor.all():
            return self.last_name
        else:
            return self.professores_mm() + ' :-) ' + self.last_name

    def __str__(self):
        return self.__concat_str__()
        #return self.last_name



def variavel_arquivo(instance, filename):
    return "painel/variavel/arquivo/{}_{}".format(instance.id, filename)

class Variavel(UUIDModelMixin, TimedModelMixin, UserModelMixin):
    nome = models.CharField("Nome",max_length=100,help_text='Sem espaços, nem acentos. Tudo minúsculo.')
    valor = models.CharField("Valor",max_length=255,blank=True,default=None,null=True,help_text='...')
    texto = models.TextField("Texto",blank=True,default=None, null=True, help_text='...')
    arquivo = models.FileField("Arquivo",blank = True, default=None, null=True, upload_to = variavel_arquivo)

    class Meta:
        unique_together = ("usuario", "nome")
        verbose_name = "Variável"
        verbose_name_plural = "Variáveis"

    def __str__(self):
        return "{}".format(self.nome)

    def get_url(self):
        if self.arquivo is not None:
            return self.arquivo.url
        else:
            return "/arquivosemcaminho/"

tarefa/models.py
from django.db import models
from django.conf import settings
import datetime


from painel.mixins import TimedModelMixin, UUIDModelMixin, UserModelMixin
from painel.models import User

from instituicao.models import Turma
from situacao.models import Problema,Simulacao,Programa,Resposta,Arquivo,Texto,Proposta


class Avaliacao(UUIDModelMixin, TimedModelMixin):
    turma = models.ForeignKey(Turma,related_name="avaliacoes",on_delete = models.CASCADE)
    nome = models.CharField(max_length = 255)
    inicio = models.DateTimeField('Data Início',help_text='...')
    fim = models.DateTimeField('Data Fim',help_text='...')

    privada = models.BooleanField(default = True)
    ativo = models.BooleanField("Ativa",default = True,help_text='...')
    nota = models.PositiveSmallIntegerField('Nota',default=1,help_text='...')

    def __str__(self):
        return '{} > {}.'.format(self.turma,self.nome)

    class Meta:
        unique_together = ("turma", "nome")
        ordering = ["turma", "nome","inicio"]
        verbose_name = "Avaliação"
        verbose_name_plural = "Avaliações"

class Questao(UUIDModelMixin, TimedModelMixin):
    avaliacao = models.ForeignKey(Avaliacao,related_name="questoes",related_query_name="campo_avaliacao",on_delete = models.CASCADE)
    problema = models.ForeignKey(Problema,related_name="na_questao",on_delete = models.CASCADE)

    ativo = models.BooleanField("Ativa",default=True,help_text='...')
    tentativa = models.PositiveSmallIntegerField('Tentativa',default=3,null=True,blank=True,help_text='...')
    tempo = models.TimeField("Tempo",default=datetime.time(2, 00),null=True,blank=True,help_text='...')# Pode ser None por causa dos projetos. Até fechar avaliacao
    nota = models.PositiveSmallIntegerField('Nota',default=1,help_text='...')

    numero = models.IntegerField("Numero",editable=False)

    def __str__(self):
        return '{} > {} > {}.'.format(self.avaliacao,self.problema,self.numero)

    class Meta:
        ordering = ["avaliacao__nome", "problema__referencia"]
        verbose_name = "Questão"
        verbose_name_plural = "Questões"

    def save(self, *args, **kwargs):
        if self.numero is None:
            turma=Turma.objects.get(id=self.avaliacao.turma.id)
            turma.questao = turma.questao + 1
            turma.save()
            self.numero = turma.questao
        super(Questao, self).save(*args, **kwargs)

class Aplicada(UUIDModelMixin, TimedModelMixin):
    usuario = models.ForeignKey(User, related_name="aplicadas_usuario", on_delete = models.CASCADE)
    questao = models.ForeignKey(Questao,related_name="aplicadas",on_delete = models.CASCADE)

    ativo = models.BooleanField("Ativa",default = True,help_text='...')

    def __str__(self):
        return 'AplicadaID={}'.format(self.id)

    def get_total_solucao(self):
        total=0
        for solucao in Solucao.objects.filter(aplicada=self.id) :
            if solucao.nota :
                total += solucao.nota
        return total*self.questao.nota*self.questao.avaliacao.nota

    def get_total_relatorio(self):
        total=0
        for relatorio in Relatorio.objects.filter(aplicada=self.id) :
            if relatorio.nota :
                total += relatorio.nota
        return total*self.questao.nota*self.questao.avaliacao.nota

    def get_total_anexo(self):
        total=0
        for anexo in Anexo.objects.filter(aplicada=self.id) :
            if anexo.nota :
                total += anexo.nota
        return total*self.questao.nota*self.questao.avaliacao.nota

    class Meta:
        unique_together = ("usuario","questao")
        ordering = ["questao__numero"]
        verbose_name = "Questao Aplicada"
        verbose_name_plural = "Questões Aplicadas"

class Solucao(UUIDModelMixin, TimedModelMixin):
    aplicada = models.ForeignKey(Aplicada,related_name="solucoes_aplicada",on_delete = models.CASCADE)
    resposta = models.ForeignKey(Resposta,related_name="solucoes_resposta",on_delete = models.CASCADE,help_text='...')

    ativo = models.BooleanField("Ativa",default = True,help_text='...')
    solucao = models.CharField('Valor',max_length=255,blank=True,default='',null=True,help_text='...')
    nota = models.PositiveSmallIntegerField('Nota',blank=True,default=None,null=True,help_text='...')

    def __str__(self):
        return 'SolucaoID={}'.format(self.id)

    class Meta:
        unique_together = ("aplicada","resposta")
        ordering = ["aplicada","resposta"]
        verbose_name = "Solução"
        verbose_name_plural = "Soluções"

class Relatorio(UUIDModelMixin, TimedModelMixin):
    aplicada = models.ForeignKey(Aplicada,related_name="relatorios_aplicada",on_delete = models.CASCADE)
    texto = models.ForeignKey(Texto,related_name="relatorios_texto",on_delete = models.CASCADE,help_text='...')

    relatorio = models.TextField('Relatório:',blank=True,default='',null=True,help_text='...')
    nota = models.PositiveSmallIntegerField('Nota',blank=True,default=None,null=True,help_text='...')
    ativo = models.BooleanField("Ativa",default = True,help_text='...')

    def __str__(self):
        return 'RelatorioID={}'.format(self.id)

    class Meta:
        unique_together = ("aplicada","texto")
        ordering = ["aplicada", "texto"]
        verbose_name = "Relatório"
        verbose_name_plural = "Relatórios"

def arquivo_questao(instance, filename):
    return "tarefa/anexo/arquivo/{0}_{1}".format(instance.id, filename)

class Anexo(UUIDModelMixin, TimedModelMixin):
    aplicada = models.ForeignKey(Aplicada,related_name="anexos_aplicada",on_delete = models.CASCADE)
    arquivo = models.ForeignKey(Arquivo,related_name="anexos_arquivo",on_delete = models.CASCADE,help_text='...')

    anexo = models.FileField('Arquivo:',upload_to=arquivo_questao,max_length=255,default=None,blank=True,help_text='...')
    nota = models.PositiveSmallIntegerField('Nota',blank=True,default=None,null=True,help_text='...')
    ativo = models.BooleanField("Ativa",default = True,help_text='...')

    def __str__(self):
        return 'Anexo={}'.format(self.id)

    class Meta:
        unique_together = ("aplicada","arquivo")
        ordering = ["aplicada", "arquivo"]
        verbose_name = "Anexo"
        verbose_name_plural = "Anexos"

#Algoritmo é o mesmo que questão
class Algoritmo(UUIDModelMixin, TimedModelMixin):
    avaliacao = models.ForeignKey(Avaliacao,related_name="algoritmos",on_delete = models.CASCADE)
    programa = models.ForeignKey(Programa,related_name="no_algoritmo",on_delete = models.CASCADE)

    ativo = models.BooleanField("Ativo",default = True,help_text='...')
    tempo = models.TimeField("Tempo",default=datetime.time(2, 00),null=True,blank=True,help_text='...')# Pode ser None por causa dos projetos. Até fechar avaliacao
    nota = models.PositiveSmallIntegerField('Nota',default=1,help_text='...')

    numero = models.IntegerField("Numero",editable=False)

    def __str__(self):
        return 'idAlg={}:{}'.format(self.id,self.numero)

    class Meta:
        ordering = ["avaliacao__nome", "programa__referencia"]
        verbose_name = "Algoritmo"
        verbose_name_plural = "Algoritmos"

    def save(self, *args, **kwargs):
        if self.numero is None:
            turma=Turma.objects.get(id=self.avaliacao.turma.id)
            turma.questao = turma.questao + 1
            turma.save()
            self.numero = turma.questao
        super(Algoritmo, self).save(*args, **kwargs)


#Algoritmo aplicado é o mesmo que questão aplicada
class Aplicado(UUIDModelMixin, TimedModelMixin):
    usuario = models.ForeignKey(User, related_name="aplicados_usuario", on_delete = models.CASCADE)
    algoritmo = models.ForeignKey(Algoritmo,related_name="aplicados",on_delete = models.CASCADE)

    ativo = models.BooleanField("Ativa",default = True,help_text='...')

    def __str__(self):
        return 'idApldo={}'.format(self.id)

    class Meta:
        unique_together = ("usuario","algoritmo")
        ordering = ["algoritmo__numero"]
        verbose_name = "Algoritmo Aplicado"
        verbose_name_plural = "Algoritmos Aplicados"

    def get_total_codigo(self):
        total=0
        for codigo in Codigo.objects.filter(aplicado=self.id) :
            if codigo.nota :
                total += codigo.nota
        return total*self.algoritmo.nota*self.algoritmo.avaliacao.nota



def arquivo_algoritmo(instance, filename):
    return "tarefa/AlgoritmoArquivo/{0}_{1}".format(instance.id, filename)

# Codigo é o mesmo que solucao ou relatorio ou anexo
class Codigo(UUIDModelMixin, TimedModelMixin):
    aplicado = models.ForeignKey(Aplicado,related_name="codigos_aplicado",on_delete = models.CASCADE)
    proposta = models.ForeignKey(Proposta,related_name="codigos_proposta",on_delete = models.CASCADE,help_text='...')

    conteudo = models.TextField('Conteúdo do arquivo',blank=True,default='',null=True,help_text='...')
    nota = models.PositiveSmallIntegerField('Nota',blank=True,default=None,null=True,help_text='...')
    ativo = models.BooleanField("Ativa",default = True,help_text='...')

    def __str__(self):
        return 'idCod={}'.format(self.id)

    class Meta:
        unique_together = ("aplicado", "proposta")
        verbose_name = "Codigo"
        verbose_name_plural = "Codigos"

aluno/forms.py
# -*- coding: utf8 -*-
from django import forms

class CodigoForm(forms.Form):
    entrada = forms.CharField(label='entrada.txt',required=False,widget=forms.Textarea,help_text='Cada linha simula a entrada de um valor via teclado.')
    interface = forms.CharField(label='interface.dart',required=False,widget=forms.Textarea,help_text='Na área acima digite o código que recebe os dados, chama a classe criada em solucao.dart e imprime os resultados.')
    solucao = forms.CharField(label='solucao.dart',required=False,widget=forms.Textarea,help_text='Na área acima digite a classe que recebe os valores, realiza os cálculo e fornece o resultado.')
    dados = forms.CharField(label='dados.txt',required=False,widget=forms.Textarea,help_text='Caso necessário a entrada de dados pode ser via arquivo.')

aluno/templates/aluno/editaralgoritmo.html
{%extends 'base.html' %}

{%load static from staticfiles %}

{% block titulo%}
    CAT@::Tarefa
{%endblock%}
{% block corpo%}

{% include 'cabecalho.html' %}

    <SCRIPT language=JavaScript>
    var sDays = 0;
    var sHors = {{status.tempo.hour}};
    var sMins = {{status.tempo.minute}};
    var sSecs = 0;
    function getSecs(){
      sSecs--;
      if(sSecs<0){
        sSecs=59;
        sMins--;
        if(sMins<=9)
          sMins="0"+sMins;
      }
      if(sMins=="0-1"){
        sMins=59;
        sHors--;
        if(sHors<=9)
          sHors="0"+sHors;
      }
      if(sHors=="0-1"){
        sHors=24;
        sDays--;
        if(sDays<=9)
          sDays="0"+sDays;
      }
      if(sSecs<=9)
        sSecs="0"+sSecs;
      if(sDays=="0-1"){
        sDays="00";
        sHors="00";
        sMins="00";
        sSecs="00";
        <!--clock1.innerHTML=sDays+"<font color=#000000>d </font> "+sHors+"<font color=#000000>h </font>"+sMins+"<font color=#000000>m </font>"+sSecs+"<font color=#000000>s</font>";-->
        clock1.innerHTML=sHors+"<font color=#000000>h </font>"+sMins+"<font color=#000000>m </font>"+sSecs+"<font color=#000000>s</font>";
      }else{
        <!--clock1.innerHTML=sDays+"<font color=#000000>d </font> "+sHors+"<font color=#000000>h </font>"+sMins+"<font color=#000000>m </font>"+sSecs+"<font color=#000000>s</font>";-->
        clock1.innerHTML=sHors+"<font color=#000000>h </font>"+sMins+"<font color=#000000>m </font>"+sSecs+"<font color=#000000>s</font>";
        setTimeout('getSecs()',1000);
      }
    }
    </SCRIPT>
    {%if user.is_authenticated %}

    <div class="container-fluid">
        <div class="row">
        <div class="col-sm-10 col-md-10">
            Olá {{user.get_cargo_display}} {{user.last_name}}. Hoje é {% now "d-m-Y H:i"%}.
            <small>
                ( <a href="{% url 'aluno:atuais' %}"> Atuais </a>
                | <a href="{% url 'painel:sair' %}"> Sair </a> )
            </small>

            <hr>
        </div>
        </div>
    </div> <!-- /container 2-->

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-8 col-md-10">
                <small>
                <ul class="list-unstyled">
                    <li>Algumas informações importantes:</li>
                    <ul>
                      <li>Instituição: {{aplicado.algoritmo.avaliacao.turma.conhecimento.instituicao.nome}}. Professor: {{aplicado.algoritmo.avaliacao.turma.conhecimento.usuario.last_name}}. Curso: {{aplicado.algoritmo.avaliacao.turma.conhecimento.nome}}. Turma: {{aplicado.algoritmo.avaliacao.turma.nome}}. </li>
                      <li>Avaliação: {{aplicado.algoritmo.avaliacao.nome}}, Nota {{aplicado.algoritmo.avaliacao.nota}}. Tarefa {{aplicado.algoritmo.numero}}: {{aplicado.algoritmo.problema.descricao}}, nota {{aplicado.algoritmo.nota}}.</li>
                      <li>Iniciada em {{status.iniciou|date:'d-m-Y H:i'}} com tempo total de {{aplicado.algoritmo.tempo|date:'H:i'}}. Gastou {{status.tentativa}} de {{aplicado.algoritmo.tentativa}} tentativas.</li>

                        <li>Instituição: {{aplicado.algoritmo.avaliacao.turma.conhecimento.instituicao.nome}}. Professor: {{aplicado.algoritmo.avaliacao.turma.conhecimento.usuario.last_name}}. Curso: {{aplicado.algoritmo.avaliacao.turma.conhecimento.nome}}. Turma: {{aplicado.algoritmo.avaliacao.turma.nome}}. <small>Para uso do sistema: [{{aplicado.id}}] </small></li>
                        <li> Avaliação: {{aplicado.algoritmo.avaliacao.nome}}. Tarefa: {{aplicado.algoritmo.programa.descricao}}. Número {{aplicado.algoritmo.numero}}. Valor {{aplicado.algoritmo.nota}} ponto(s). </li>
                        <li>Iniciada em {{status.iniciou|date:'d-m-Y H:i'}} e tempo de {{aplicado.algoritmo.tempo|date:'H:i'}} para desenvolvé-la.</li>
                        <li>O tempo de resolução encerrará em: <font color=#FF0000 size=4 face=arial><span id="clock1"></span><script>setTimeout('getSecs()',1000);</script></font></li>
                    </ul>
                </ul>
                </small>
                <hr>
            </div>
        </div>


        <h5>Você tem <font color=#FF0000 size=4 face=arial><span id="clock1"></span><script>setTimeout('getSecs()',1000);</script></font> para desenvolver/responder o que pede a proposta:</h5>



        <div class="row">
            <div class="col-sm-8 col-md-10">
                <div class="card">
                  <div class="card-header" id="headingOne">
                    <h5 class="mb-0">
                      <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#propostatarefa" aria-expanded="true" aria-controls="propostatarefa">
                        Proposta da tarefa
                      </button>
                    </h5>
                  </div>
                  <div id="propostatarefa" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
                    <div class="card-body">
                                <object data='/cata/media/{{aplicado.algoritmo.programa.pdf}}'
                                        type='application/pdf'
                                        width='100%'
                                        height='300px'>
                                        <p class="bg-success">
                                :-(((( SE VOCÊ ESTA LENDO ESTA MENSAGEM O SEU NAVEGADOR NÃO CONSEGUIU VISUALIZAR O PDF DA TAREFA. O PROBLEMA NÃO ESTA NO SISTEMA DE TAREFAS E SIM NO SEU NAVEGADOR DE INTERNET.</p>
                                <p class="bg-success">  <a href="/cata/media/{{aplicado.algoritmo.programa.pdf}}"  target="_blank"> CLIQUE AQUI PARA FAZER O DOWNLOAD DO ARQUIVO PDF COM A TAREFA PARA RESOLUÇÃO.</a></p>
                              </object>
                    </div>
                  </div>
                </div>
            </div>
        </div>

        <form action="{% url 'aluno:editaralgoritmo' aplicado.id %}" method="POST" enctype="multipart/form-data">{% csrf_token %}



            <div class="row">
                <div class="col-sm-8 col-md-10">
                    <hr>

                    #Entrada. Simulador de teclado.
                    {% for codigo in aplicado.codigos_aplicado.all %}
                        {% if codigo.ativo and codigo.proposta.arquivo == 'entrada.txt'%}
                            <textarea id="id_entrada" name="entrada" rows="5" cols="62">{{codigo.conteudo}}</textarea>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8 col-md-10">
                    interface.dart</br>
                    {% for codigo in aplicado.codigos_aplicado.all %}
                        {% if codigo.ativo  and codigo.proposta.arquivo == 'interface.dart' %}
                            <textarea id="id_interface" name="interface" rows="5" cols="62">{{codigo.conteudo}}</textarea>
                        {% endif %}
                    {% endfor %}

                    solucao.dart</br>
                    {% for codigo in aplicado.codigos_aplicado.all %}
                        {% if codigo.ativo  and codigo.proposta.arquivo == 'solucao.dart' %}
                            <textarea id="id_solucao" name="solucao" rows="5" cols="62">{{codigo.conteudo}}</textarea>
                        {% endif %}
                    {% endfor %}

                    #Saida. Simulador do Monitor ou Video</br>
                    <textarea id="id_saida" name="saida" rows="5" cols="62">{{saida}}</textarea>

                    <hr>
                    Dados.txt</br>
                    {% for codigo in aplicado.codigos_aplicado.all %}
                        {% if codigo.ativo and codigo.proposta.arquivo == 'dados.txt'%}
                            <textarea id="id_dados" name="dados" rows="5" cols="62">{{codigo.conteudo}}</textarea>
                        {% endif %}
                    {% endfor %}

                    Relatorio.</br>
                    <textarea id="id_relatorio" name="relatorio" rows="5" cols="62">{{relatorio}}</textarea>
                    <hr>

                </div>
            </div>

            <div class="row">
                <div class="col-sm-8 col-md-10">
                    <button type="submit" class="btn btn-success">
                        SALVAR O CÓDIGO.
                    </button>
                </div>
            </div>
        <form>
        <!--
          , EXECUTAR, ANALISAR E TESTAR
            <div class="row">
                <div class="col-sm-8 col-md-10">
                    <hr>
                    {% if output %}
                      Erro no código:
                      <pre>  {{output|linebreaksbr|safe}} </pre>
                    {% else %}
                      Sem erro no código.
                    {% endif %}
                    <hr>
                    {% if passou_testes == None %}
                        Sem testes.
                    {% elif passou_testes %}
                        Passou em todos os testes.
                    {% else %}
                        Não passou nos testes.
                    {% endif %}
                    <hr>

                </div>
            </div>-->

    </div> <!-- /container -->


{%else%}
</br></br>Acesso não permitido. Favor procurar o Professor desta turma.
{%endif%}



    <script>
        var editor = CodeMirror.fromTextArea(document.getElementById("id_interface"), {
          lineNumbers: true,
          mode: "dart",
          matchBrackets: true,
          lineWiseCopyCut: false,
          tabSize: 2,
        });
        // editor.on("beforeChange", function(_, change) { if (change.origin == "paste") change.cancel() })
        editor.setOption("extraKeys", {
      Tab: function(cm) {
        var spaces = Array(cm.getOption("indentUnit") + 1).join(" ");
        cm.replaceSelection(spaces);
      }
    });

        var editor2 = CodeMirror.fromTextArea(document.getElementById("id_solucao"), {
          lineNumbers: true,
          mode: "dart",
          matchBrackets: true,
          lineWiseCopyCut: false,
          tabSize: 2,
          indentUnit:2,
        });
        // editor2.on("beforeChange", function(_, change) { if (change.origin == "paste") change.cancel() })
        editor2.setOption("extraKeys", {
      Tab: function(cm) {
        var spaces = Array(cm.getOption("indentUnit") + 1).join(" ");
        cm.replaceSelection(spaces);
      }
    });

        var editor3 = CodeMirror.fromTextArea(document.getElementById("id_entrada"), {
          lineNumbers: true,
          mode: "text",
          matchBrackets: true,
          lineWiseCopyCut: false,
          tabSize: 2,
        });
        editor3.setOption("extraKeys", {
      Tab: function(cm) {
        var spaces = Array(cm.getOption("indentUnit") + 1).join(" ");
        cm.replaceSelection(spaces);
      }
    });

    var editor3 = CodeMirror.fromTextArea(document.getElementById("id_dados"), {
      lineNumbers: true,
      mode: "text",
      matchBrackets: true,
      lineWiseCopyCut: false,
      tabSize: 2,
    });
    editor3.setOption("extraKeys", {
    Tab: function(cm) {
    var spaces = Array(cm.getOption("indentUnit") + 1).join(" ");
    cm.replaceSelection(spaces);
    }
    });

    var editor3 = CodeMirror.fromTextArea(document.getElementById("id_saida"), {
      lineNumbers: true,
      mode: "text",
      matchBrackets: true,
      lineWiseCopyCut: false,
      tabSize: 2,
    });
    editor3.setOption("extraKeys", {
    Tab: function(cm) {
    var spaces = Array(cm.getOption("indentUnit") + 1).join(" ");
    cm.replaceSelection(spaces);
    }
    });

    var editor3 = CodeMirror.fromTextArea(document.getElementById("id_relatorio"), {
      lineNumbers: true,
      mode: "text",
      matchBrackets: true,
      lineWiseCopyCut: false,
      tabSize: 2,
    });
    editor3.setOption("extraKeys", {
    Tab: function(cm) {
    var spaces = Array(cm.getOption("indentUnit") + 1).join(" ");
    cm.replaceSelection(spaces);
    }
    });

    </script>



{%endblock%}