api/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from api.views import VersaoAPIView

app_name = 'api'

urlpatterns = [
    path('versao/', VersaoAPIView.as_view(), name='versao'),
    path('auth/', include('api.urls_auth')),
    path('docs/', include('api.urls_docs')),

    path('instituicao/', include('instituicao.urls_api')),
    path('painel/', include('painel.urls_api')),
    path('professor/', include('professor.urls_api')),
    path('situacao/', include('situacao.urls_api')),
    path('tarefa/', include('tarefa.urls_api')),

]

cata/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('api/', include("api.urls")),


    path('aluno/', include('aluno.urls')),
    path('professor/', include('professor.urls')),
    path('instituicao/', include('instituicao.urls')),
    path('situacao/', include('situacao.urls')),
    path('tarefa/', include('tarefa.urls')),
    path('', include('painel.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#path('cata/tarefa/', include('tarefa.urls')),

painel/urls.py
from django.urls import path

from . import views

app_name = "painel"

urlpatterns = [
    path("", views.index, name = "index"),
    path("sair/", views.sair, name = "sair"),
    path("alunonovo/<uuid:id>", views.alunonovo, name = "alunonovo"),
    path("alunoeditar/<uuid:id>", views.alunoeditar, name = "alunoeditar"),
    path("senhanova/", views.senhanova, name = "senhanova"),
    path("senhareset/<uuid:id>", views.senhareset, name = "senhareset"),
]

professor/urls.py
from django.urls import path

from . import views

app_name = "professor"

urlpatterns = [
    path("acoes/", views.acoes, name = "acoes"),
    path("conhecimento/", views.conhecimento, name = "conhecimento"),
    path("indice/", views.indice, name = "indice"),
    path("notas/", views.notas, name = "notas"),
    path("alunotarefas/<uuid:idturma>/<uuid:idaluno>", views.alunotarefas, name = "alunotarefas"),
    path("ementa/", views.ementa, name = "ementa"),
    path("ementaeditar/<uuid:id>", views.ementaeditar, name = "ementaeditar"),
]

tarefa/urls.py
from django.urls import path


from . import views

app_name = "tarefa"

urlpatterns = [
    path("avaliacaonovo/<uuid:id>", views.avaliacaonovo, name = "avaliacaonovo"),
    path("avaliacaoeditar/<uuid:id>", views.avaliacaoeditar, name = "avaliacaoeditar"),
    path("questaonovo/<uuid:id>", views.questaonovo, name = "questaonovo"),
    path("questaoeditar/<uuid:id>", views.questaoeditar, name = "questaoeditar"),
    path("relatoriocorrigir1/<uuid:id>", views.relatoriocorrigir1, name = "relatoriocorrigir1"),
    path("relatoriocorrigir2/", views.relatoriocorrigir2, name = "relatoriocorrigir2"),
    path("anexocorrigir1/<uuid:id>", views.anexocorrigir1, name = "anexocorrigir1"),
    path("anexocorrigir2/", views.anexocorrigir2, name = "anexocorrigir2"),
    path("aplicadaeditar/<uuid:id>", views.aplicadaeditar, name = "aplicadaeditar"),
    path("aplicadoeditar/<uuid:id>", views.aplicadoeditar, name = "aplicadoeditar"),
    path("avaliacaoaplicar1/<uuid:id>", views.avaliacaoaplicar1, name = "avaliacaoaplicar1"),
    path("avaliacaoaplicar2/<uuid:id>", views.avaliacaoaplicar2, name = "avaliacaoaplicar2"),
    path("relatorio/<uuid:id>", views.relatorio, name = "relatorio"),
    path("apagar/<uuid:id>", views.apagar, name = "apagar"),
    path("algoritmonovo/<uuid:id>", views.algoritmonovo, name = "algoritmonovo"),
    path("algoritmoeditar/<uuid:id>", views.algoritmoeditar, name = "algoritmoeditar"),
    path("codigo/<uuid:id>", views.codigo, name = "codigo"),
    path("codigocorrigir1/<uuid:id>", views.codigocorrigir1, name = "codigocorrigir1"),
    path("codigocorrigir2/", views.codigocorrigir2, name = "codigocorrigir2"),
    path("codigotestar/<uuid:id>", views.codigotestar, name = "codigotestar"),
    path("valoresaleatoriosver/<uuid:id>", views.valoresaleatoriosver, name = "valoresaleatoriosver"),
]

painel/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser, UserManager

from painel.mixins import TimedModelMixin, UUIDModelMixin, UserModelMixin

class User(AbstractUser, UUIDModelMixin):
    CARGO=(('professor','Professor(a)'),('aluno','Aluno(a)'),('admin','Administrador(a)'),)

    # cargo
    cargo = models.CharField('Cargo',max_length=25,choices=CARGO)
    professor = models.ManyToManyField('self',symmetrical=False,related_name="professores",blank=True,default=None)

    objects = UserManager()

    class Meta:
        ordering = ["last_name"]
        verbose_name = "User"
        verbose_name_plural = "Users"

    def professores_mm(self):
        return " ".join(['*{} '.format(p.last_name) for p in self.professor.all()])

    def __concat_str__(self):
        if not self.professor.all():
            return self.last_name
        else:
            return self.professores_mm() + ' :-) ' + self.last_name

    def __str__(self):
        return self.__concat_str__()
        #return self.last_name



def variavel_arquivo(instance, filename):
    return "painel/variavel/arquivo/{}_{}".format(instance.id, filename)

class Variavel(UUIDModelMixin, TimedModelMixin, UserModelMixin):
    nome = models.CharField("Nome",max_length=100,help_text='Sem espaços, nem acentos. Tudo minúsculo.')
    valor = models.CharField("Valor",max_length=255,blank=True,default=None,null=True,help_text='...')
    texto = models.TextField("Texto",blank=True,default=None, null=True, help_text='...')
    arquivo = models.FileField("Arquivo",blank = True, default=None, null=True, upload_to = variavel_arquivo)

    class Meta:
        unique_together = ("usuario", "nome")
        verbose_name = "Variável"
        verbose_name_plural = "Variáveis"

    def __str__(self):
        return "{}".format(self.nome)

    def get_url(self):
        if self.arquivo is not None:
            return self.arquivo.url
        else:
            return "/arquivosemcaminho/"

tarefa/forms.py
# -*- coding: utf8 -*-
from django import forms

from tarefa.models import Avaliacao,Questao,Aplicada,Solucao,Relatorio,Anexo,Algoritmo,Codigo,Aplicado
from instituicao.models import Conhecimento,Turma
from situacao.models import Indice,Problema,Simulacao,ValorAleatorio,Resposta,Arquivo,Texto,Programa,Teste

class AvaliacaoForm(forms.ModelForm):
    class Meta:
        model = Avaliacao
        fields=['nome','inicio','fim','privada','ativo','nota',]

class QuestaoForm(forms.ModelForm):
    class Meta:
        model = Questao
        fields=['problema','ativo','tentativa','tempo','nota',]
    def __init__(self, user, avaliacao, *args, **kwargs):
        super(QuestaoForm, self).__init__(*args, **kwargs)
        self.fields['problema'].queryset = Problema.objects.filter(usuario=user,ativo=True,indices__in=avaliacao.turma.conhecimento.indices.all())

class AlgoritmoForm(forms.ModelForm):
    class Meta:
        model = Algoritmo
        fields=['programa','ativo','tempo','nota',]
    def __init__(self, user, avaliacao, *args, **kwargs):
        super(AlgoritmoForm, self).__init__(*args, **kwargs)
        self.fields['programa'].queryset = Programa.objects.filter(usuario=user,ativo=True,indices__in=avaliacao.turma.conhecimento.indices.all())

tarefa/views.py
from django.shortcuts import render
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,render_to_response
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse

import threading

from django.conf import settings
import os
from os import kill
from subprocess import PIPE, Popen

from datetime import date,timedelta,datetime,timezone
import os
from django.conf import settings
from django.core.files.storage import FileSystemStorage
import random

from instituicao.models import Instituicao,Conhecimento,Turma
from tarefa.models import Avaliacao,Questao,Aplicada,Solucao,Relatorio,Anexo,Algoritmo,Codigo,Aplicado
from tarefa.forms import AvaliacaoForm,QuestaoForm,AlgoritmoForm
from situacao.models import Indice,Problema,Simulacao,ValorAleatorio,Resposta,Arquivo,Texto,Programa,Teste
from professor.models import QuestaoStatus,AlgoritmoStatus
from painel.models import User


@login_required
def avaliacaonovo(request,id):
    if request.method == 'POST':
        form=AvaliacaoForm(request.POST)
        if form.is_valid():
            novo=form.save(commit=False)
            novo.turma=Turma.objects.get(id=id)
            novo.save()
            return HttpResponseRedirect(reverse('professor:conhecimento'))
    else:
        form=AvaliacaoForm()
    context = {'form':form,'id':id}
    return render(request, 'tarefa/avaliacaonovo.html', context)

@login_required
def avaliacaoeditar(request,id):
    avaliacao=Avaliacao.objects.get(id=id)
    if request.method == 'POST':
        form=AvaliacaoForm(request.POST,instance=avaliacao)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('professor:conhecimento'))
    else:
        form = AvaliacaoForm(instance=avaliacao)
    context = {'form':form,'id':avaliacao.id,'tempo':avaliacao}
    return render(request, 'tarefa/avaliacaoeditar.html', context)


@login_required
def avaliacaoaplicar1(request,id):
    avaliacao=Avaliacao.objects.get(id=id)
    alunos=avaliacao.turma.alunos.all()
    context = {'alunos':alunos,'avaliacao':avaliacao,'id':id}
    return render(request, 'tarefa/avaliacaoaplicar1.html', context)


def aplicar(alunos, avaliacao):
    for questao in avaliacao.questoes.all() :
        lista=questao.problema.simulacoes.all()
        for idaluno in alunos :
            aluno=User.objects.get(id=idaluno)
            if not Aplicada.objects.filter(usuario=aluno,questao=questao).exists():
                aplicada,criado = Aplicada.objects.get_or_create(usuario=aluno,questao=questao)
                status,criado = QuestaoStatus.objects.get_or_create(aplicada=aplicada)
                if lista:
                    simulacao=random.choice(lista)
                    for resposta in simulacao.respostas.all() :
                        solucao,criado = Solucao.objects.get_or_create(aplicada=aplicada,resposta=resposta)
                    for texto in simulacao.textos.all() :
                        relatorio,criado = Relatorio.objects.get_or_create(aplicada=aplicada,texto=texto)
                    for arquivo in simulacao.arquivos.all() :
                        anexo,criado = Anexo.objects.get_or_create(aplicada=aplicada,arquivo=arquivo)
                else:
                    context={}
                    return render(request, 'tarefa/avaliacaoaplicar2.html', context)
            questao.problema.get_usos()

    for algoritmo in avaliacao.algoritmos.all() :
        for idaluno in alunos :
            aluno=User.objects.get(id=idaluno)
            if not Aplicado.objects.filter(usuario=aluno,algoritmo=algoritmo).exists():
                aplicado,criado = Aplicado.objects.get_or_create(usuario=aluno,algoritmo=algoritmo)
                status,criado = AlgoritmoStatus.objects.get_or_create(aplicado=aplicado)
                for proposta in algoritmo.programa.propostas.all() :
                    codigo,criado = Codigo.objects.get_or_create(aplicado=aplicado,proposta=proposta)
            algoritmo.programa.get_usos()

class minhaThread (threading.Thread):
    def __init__(self, alunos, avaliacao):
        threading.Thread.__init__(self)
        self.alunos = alunos
        self.avaliacao = avaliacao
    def run(self):
        # print('run')
        aplicar(self.alunos, self.avaliacao)

@login_required
def avaliacaoaplicar2(request,id):
    avaliacao=Avaliacao.objects.get(id=id)
    if request.method == 'POST':
        idalunos = request.POST.getlist('alunos')
        # print(f'{idalunos} = {avaliacao}')
        thread1 = minhaThread(idalunos, avaliacao)
        thread1.start()

    return HttpResponseRedirect(reverse('professor:conhecimento'))



@login_required
def questaonovo(request,id):
    avaliacao=Avaliacao.objects.get(id=id)
    if request.method == 'POST':
        form=QuestaoForm(request.user,avaliacao,request.POST)
        if form.is_valid():
            novo=form.save(commit=False)
            novo.avaliacao=avaliacao
            novo.save()
            return HttpResponseRedirect(reverse('professor:conhecimento'))
    else:
        form=QuestaoForm(request.user,avaliacao)
    context = {'form':form,'id':id}
    return render(request, 'tarefa/questaonovo.html', context)

@login_required
def questaoeditar(request,id):
    questao=Questao.objects.get(id=id)
    avaliacao=questao.avaliacao
    if request.method == 'POST':
        form=QuestaoForm(request.user,avaliacao,request.POST,instance=questao)
        if form.is_valid():
            form.save()
            for aplicada in questao.aplicadas.all() :
                for status in aplicada.status.all() :
                    status.iniciou = None
                    status.save()
            return HttpResponseRedirect(reverse('professor:conhecimento'))
    else:
        form = QuestaoForm(request.user,avaliacao,instance=questao)
    context = {'form':form,'id':questao.id}
    return render(request, 'tarefa/questaoeditar.html', context)


@login_required
def relatoriocorrigir1(request,id):
    questao=Questao.objects.get(id=id)
    aplicadas=questao.aplicadas.all()
    for aplicada in aplicadas :
        ## print("{}|{}".format(aplicada.id,aplicada.usuario))
        for relatorio in aplicada.relatorios_aplicada.all():
            ## print("{}|{}|{}".format(relatorio.id,relatorio.relatorio,relatorio.nota))
            relatorio.nota = 0
            relatorio.save()
    context = {'aplicadas':aplicadas}
    return render(request, 'tarefa/relatoriocorrigir1.html', context)

@login_required
def relatoriocorrigir2(request):
    if request.method == 'POST':
        corrigidos = request.POST.getlist('corrigidos')
        for corrigido in corrigidos :
            a=Relatorio.objects.get(id=corrigido)
            a.nota=1
            a.save()
    return HttpResponseRedirect(reverse('professor:conhecimento'))

@login_required
def anexocorrigir1(request,id):
    questao=Questao.objects.get(id=id)
    aplicadas=questao.aplicadas.all()
    for aplicada in aplicadas :
        ## print("{}|{}".format(aplicada.id,aplicada.usuario))
        for anexo in aplicada.anexos_aplicada.all():
            ## print("{}|{}|{}".format(anexo.id,anexo.anexo,anexo.nota))
            anexo.nota = 0
            anexo.save()
    context = {'aplicadas':aplicadas}
    return render(request, 'tarefa/anexocorrigir1.html', context)

@login_required
def anexocorrigir2(request):
    if request.method == 'POST':
        corrigidos = request.POST.getlist('corrigidos')
        for corrigido in corrigidos :
            a=Anexo.objects.get(id=corrigido)
            a.nota=1
            a.save()
    return HttpResponseRedirect(reverse('professor:conhecimento'))


@login_required
def aplicadaeditar(request,id):
    aplicada=Aplicada.objects.get(id=id)
    aplicada.ativo= not aplicada.ativo
    aplicada.save()
    context={}
    return render(request, 'tarefa/ok.html', context)


@login_required
def aplicadoeditar(request,id):
    aplicado=Aplicado.objects.get(id=id)
    aplicado.ativo= not aplicado.ativo
    aplicado.save()
    context={}
    return render(request, 'tarefa/ok.html', context)


@login_required
def relatorio(request,id):
    relatorio=Relatorio.objects.get(id=id)
    context = {'relatorio':relatorio}
    return render(request, 'tarefa/relatorio.html', context)



@login_required
def algoritmonovo(request,id):
    avaliacao=Avaliacao.objects.get(id=id)
    if request.method == 'POST':
        form=AlgoritmoForm(request.user,avaliacao,request.POST)
        if form.is_valid():
            novo=form.save(commit=False)
            novo.avaliacao=avaliacao
            novo.save()
            return HttpResponseRedirect(reverse('professor:conhecimento'))
    else:
        form=AlgoritmoForm(request.user,avaliacao)
    context = {'form':form,'id':id}
    return render(request, 'tarefa/algoritmonovo.html', context)

@login_required
def algoritmoeditar(request,id):
    algoritmo=Algoritmo.objects.get(id=id)
    avaliacao=algoritmo.avaliacao
    if request.method == 'POST':
        form=AlgoritmoForm(request.user,avaliacao,request.POST,instance=algoritmo)
        if form.is_valid():
            form.save()
            for aplicado in algoritmo.aplicados.all() :
                for status in aplicado.status_aplicado.all() :
                    status.iniciou = None
                    status.save()
            return HttpResponseRedirect(reverse('professor:conhecimento'))
    else:
        form = AlgoritmoForm(request.user,avaliacao,instance=algoritmo)
    context = {'form':form,'id':algoritmo.id}
    return render(request, 'tarefa/algoritmoeditar.html', context)


@login_required
def codigo(request,id):
    codigo=Codigo.objects.get(id=id)
    context = {'codigo':codigo}
    return render(request, 'tarefa/codigo.html', context)



def execcmd(args, cwd = None, shell = False, kill_tree = True, timeout = -1, env = None):
    '''

tarefa/templates/tarefa/algoritmoeditar.html
{%extends 'base.html' %}

{%load static from staticfiles %}

{% block titulo%}
    CAT@::Ações Prof
{%endblock%}
{% block corpo%}

{% include 'cabecalho.html' %}

    {%if user.is_authenticated %}
        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-10 col-md-10">
                Olá {{user.get_cargo_display}} {{user.last_name}}. Hoje é {% now "d-m-Y H:i"%}.
                <small>
                  ( <a href="{% url 'professor:conhecimento' %}"> Conhecimentos </a> )
                </small>
                <hr>
            </div>
            </div>
        </div> <!-- /container 1-->

        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-10 col-md-10">
                <h3>Editar este algoritmo.</h3><small>Para apagar este item e todos ligados a ele clique nos três pontinhos <a href={% url 'tarefa:apagar' id %}  title='Se clicar aqui todos os itens ligados a este serão apagados.'> ...</a></small></br></br>
                <form action="{% url 'tarefa:algoritmoeditar' id %}" method="POST" enctype="multipart/form-data">{%csrf_token%}
                  {% include 'formvictor.html' with form=form %}
                    <input type="submit" value="Enviar informações" />
                </form>
            </div>
            </div>
        </div> <!-- /container 2-->



        {%else%}
            </br></br>Acesso não permitido. Favor procurar o Professor desta turma.
        {%endif%}

    {%endblock%}

tarefa/templates/tarefa/algoritmonovo.html
{%extends 'base.html' %}

{%load static from staticfiles %}

{% block titulo%}
    CAT@::Ações Prof
{%endblock%}
{% block corpo%}

{% include 'cabecalho.html' %}

    {%if user.is_authenticated %}
        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-10 col-md-10">
                Olá {{user.get_cargo_display}} {{user.last_name}}. Hoje é {% now "d-m-Y H:i"%}.
                <small>
                  ( <a href="{% url 'professor:conhecimento' %}"> Conhecimentos </a> )
                </small>
                <hr>
            </div>
            </div>
        </div> <!-- /container 1-->

        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-10 col-md-10">
                <h3>Cadastro de novo algoritmo.</h3>
                <form action="{% url 'tarefa:algoritmonovo' id %}" method="POST" enctype="multipart/form-data">{%csrf_token%}
                  {% include 'formvictor.html' with form=form %}
                    <input type="submit" value="Enviar informações" />
                </form>
            </div>
            </div>
        </div> <!-- /container 2-->

        {%else%}
            </br></br>Acesso não permitido. Favor procurar o Professor desta turma.
        {%endif%}

    {%endblock%}

tarefa/templates/tarefa/avaliacaoaplicar2.html
{%extends 'base.html' %}

{%load static from staticfiles %}

{% block titulo%}
    CAT@::Ações Prof
{%endblock%}
{% block corpo%}

{% include 'cabecalho.html' %}

    {%if user.is_authenticated %}
        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-10 col-md-10">
                Olá {{user.get_cargo_display}} {{user.last_name}}. Hoje é {% now "d-m-Y H:i"%}.
                <small>
                    ( <a href="{% url 'professor:acoes' %}"> Ações do professor </a> )
                </small>
                <hr>
            </div>
            </div>
        </div> <!-- /container 1-->

        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-10 col-md-10">
                <h3>Este problema não tem simulações impossivel aplicar aos alunos.</h3>
                <h4> Volte em Gerenciar Índices e Situações e crie simulações para este problema</h4>

            </div>
            </div>
        </div> <!-- /container 2-->

        {%else%}
            </br></br>Acesso não permitido. Favor procurar o Professor desta turma.
        {%endif%}

    {%endblock%}

tarefa/templates/tarefa/avaliacaoeditar.html
{%extends 'base.html' %}

{%load static from staticfiles %}

{% block titulo%}
    CAT@::Ações Prof
{%endblock%}
{% block corpo%}

{% include 'cabecalho.html' %}

    {%if user.is_authenticated %}
        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-10 col-md-10">
                Olá {{user.get_cargo_display}} {{user.last_name}}. Hoje é {% now "d-m-Y H:i"%}.
                <small>
                  ( <a href="{% url 'professor:conhecimento' %}"> Conhecimentos </a> )
                </small>
                <hr>
            </div>
            </div>
        </div> <!-- /container 1-->

        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-10 col-md-10">
                <h3>Editar esta avaliacao.</h3><small>Para apagar este item e todos ligados a ele clique nos três pontinhos <a href={% url 'tarefa:apagar' id %}  title='Se clicar aqui todos os itens ligados a este serão apagados.'> ...</a></small></br></br>
                <form action="{% url 'tarefa:avaliacaoeditar' id %}" method="POST" enctype="multipart/form-data">{%csrf_token%}
                  {% include 'formvictor.html' with form=form %}
                    <input type="submit" value="Enviar informações" />
                </form>
            </div>
            </div>
        </div> <!-- /container 2-->



        {%else%}
            </br></br>Acesso não permitido. Favor procurar o Professor desta turma.
        {%endif%}


    {%endblock%}

tarefa/templates/tarefa/codigocorrigir1.html
{%extends 'base.html' %}

{%load static from staticfiles %}

{% block titulo%}
    CAT@::Ações Prof
{%endblock%}
{% block corpo%}

{% include 'cabecalho.html' %}

    {%if user.is_authenticated %}
        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-10 col-md-10">
                Olá {{user.get_cargo_display}} {{user.last_name}}. Hoje é {% now "d-m-Y H:i"%}.
                <small>
                    ( <a href="{% url 'professor:acoes' %}"> Ações do professor </a> )
                </small>
                <hr>
            </div>
            </div>
        </div> <!-- /container 1-->

        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-10 col-md-10">
                <h3>Codigos a serem corrigidos.</h3>
                <form action="{% url 'tarefa:codigocorrigir2' %}" method="POST" enctype="multipart/form-data">{%csrf_token%}

                {% for aplicado in aplicados %}
                    {% for codigo in aplicado.codigos_aplicado.all %}
                        Usuario: {{aplicado.usuario}}</br>
                        Avaliacao: {{aplicado.algoritmo.avaliacao.nome}}</br>
                        Programa: {{aplicado.algoritmo.programa.referencia}}</br>
                        Arquivo: {{codigo.proposta.arquivo}}</br>
                        Nota: {{codigo.nota}}
                        <input type="checkbox" {%if codigo.conteudo|length >= 1 %} checked	{%endif%} name="corrigidos" value="{{codigo.id}}"></input>
                        <hr>

                        <textarea rows="5" cols="100">{{codigo.conteudo}}</textarea>
                        <hr>
                        <hr>
                    {% endfor %}
                    =====================================</br>
                {% endfor %}
                <input type="submit" value="Enviar informações" />
                </form>

            </div>
            </div>
        </div> <!-- /container 2-->

        {%else%}
            </br></br>Acesso não permitido. Favor procurar o Professor desta turma.
        {%endif%}

    {%endblock%}

tarefa/templates/tarefa/ok.html
{%extends 'base.html' %}

{%load static from staticfiles %}

{% block titulo%}
    CAT@::Ações Prof
{%endblock%}
{% block corpo%}

{% include 'cabecalho.html' %}

    {%if user.is_authenticated %}
        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-10 col-md-10">
                Olá {{user.get_cargo_display}} {{user.last_name}}. Hoje é {% now "d-m-Y H:i"%}.
                <small>
                  ( <a href="{% url 'professor:acoes' %}"> Ações </a> |
                   <a href="{% url 'professor:conhecimento' %}"> Conhecimentos </a> |
                   <a href="{% url 'painel:sair' %}"> Sair </a> )                </small>
                </small>
                <hr>
            </div>
            </div>
        </div> <!-- /container 1-->

        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-10 col-md-10">
                <h3>Alteração feita com sucesso</h3>
            </div>
            </div>
        </div> <!-- /container 2-->

        {%else%}
            </br></br>Acesso não permitido. Favor procurar o Professor desta turma.
        {%endif%}

    {%endblock%}

tarefa/templates/tarefa/questaoeditar.html
{%extends 'base.html' %}

{%load static from staticfiles %}

{% block titulo%}
    CAT@::Ações Prof
{%endblock%}
{% block corpo%}

{% include 'cabecalho.html' %}

    {%if user.is_authenticated %}
        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-10 col-md-10">
                Olá {{user.get_cargo_display}} {{user.last_name}}. Hoje é {% now "d-m-Y H:i"%}.
                <small>
                  ( <a href="{% url 'professor:conhecimento' %}"> Conhecimentos </a> )
                </small>
                <hr>
            </div>
            </div>
        </div> <!-- /container 1-->

        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-10 col-md-10">
                <h3>Editar esta questão.</h3><small>Para apagar este item e todos ligados a ele clique nos três pontinhos <a href={% url 'tarefa:apagar' id %}  title='Se clicar aqui todos os itens ligados a este serão apagados.'> ...</a></small></br></br>
                <form action="{% url 'tarefa:questaoeditar' id %}" method="POST" enctype="multipart/form-data">{%csrf_token%}
                  {% include 'formvictor.html' with form=form %}
                    <input type="submit" value="Enviar informações" />
                </form>
            </div>
            </div>
        </div> <!-- /container 2-->



        {%else%}
            </br></br>Acesso não permitido. Favor procurar o Professor desta turma.
        {%endif%}

    {%endblock%}