aluno/urls.py
from django.urls import path

from . import views

app_name = "aluno"

urlpatterns = [
    path("atuais/", views.atuais, name = "atuais"),
    path("todas/", views.todas, name = "todas"),
    path("editar/<uuid:id>", views.editar, name = "editar"),
    path("editaralgoritmo/<uuid:id>", views.editaralgoritmo, name = "editaralgoritmo"),
    path("publica", views.publica, name = "publica"),
]

api/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from api.views import VersaoAPIView

app_name = 'api'

urlpatterns = [
    path('versao/', VersaoAPIView.as_view(), name='versao'),
    path('auth/', include('api.urls_auth')),
    path('docs/', include('api.urls_docs')),

    path('instituicao/', include('instituicao.urls_api')),
    path('painel/', include('painel.urls_api')),
    path('professor/', include('professor.urls_api')),
    path('situacao/', include('situacao.urls_api')),
    path('tarefa/', include('tarefa.urls_api')),

]

cata/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('api/', include("api.urls")),


    path('aluno/', include('aluno.urls')),
    path('professor/', include('professor.urls')),
    path('instituicao/', include('instituicao.urls')),
    path('situacao/', include('situacao.urls')),
    path('tarefa/', include('tarefa.urls')),
    path('', include('painel.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#path('cata/tarefa/', include('tarefa.urls')),

painel/urls.py
from django.urls import path

from . import views

app_name = "painel"

urlpatterns = [
    path("", views.index, name = "index"),
    path("sair/", views.sair, name = "sair"),
    path("alunonovo/<uuid:id>", views.alunonovo, name = "alunonovo"),
    path("alunoeditar/<uuid:id>", views.alunoeditar, name = "alunoeditar"),
    path("senhanova/", views.senhanova, name = "senhanova"),
    path("senhareset/<uuid:id>", views.senhareset, name = "senhareset"),
]

professor/urls.py
from django.urls import path

from . import views

app_name = "professor"

urlpatterns = [
    path("acoes/", views.acoes, name = "acoes"),
    path("conhecimento/", views.conhecimento, name = "conhecimento"),
    path("indice/", views.indice, name = "indice"),
    path("notas/", views.notas, name = "notas"),
    path("alunotarefas/<uuid:idturma>/<uuid:idaluno>", views.alunotarefas, name = "alunotarefas"),
    path("ementa/", views.ementa, name = "ementa"),
    path("ementaeditar/<uuid:id>", views.ementaeditar, name = "ementaeditar"),
]

situacao/urls.py
from django.urls import path

from . import views

app_name = "situacao"

#path("indicenovo/", views.indicenovo, name = "indicenovo"),
urlpatterns = [
    path("indiceitem/<uuid:id>", views.indiceitem, name = "indiceitem"),
    path("indicesubitem/<uuid:id>", views.indicesubitem, name = "indicesubitem"),
    path("indiceeditar/<uuid:id>", views.indiceeditar, name = "indiceeditar"),
    path("sobe/<uuid:id>", views.sobe, name = "sobe"),
    path("desce/<uuid:id>", views.desce, name = "desce"),
    path("problemanovo/<uuid:id>", views.problemanovo, name = "problemanovo"),
    path("problemaeditar/<uuid:id>", views.problemaeditar, name = "problemaeditar"),
    path("texto/<uuid:id>", views.texto, name = "texto"),
    path("simulacao/<uuid:id>", views.simulacao, name = "simulacao"),
    path("simulacaonovo/<uuid:id>", views.simulacaonovo, name = "simulacaonovo"),
    path("simulacaoapagar/<uuid:id>", views.simulacaoapagar, name = "simulacaoapagar"),
    path("simulacaoapagartodas/<uuid:id>", views.simulacaoapagartodas, name = "simulacaoapagartodas"),
    path("simulacaoimportar/<uuid:id>", views.simulacaoimportar, name = "simulacaoimportar"),
    path("vlraleatnovo/<uuid:id>", views.vlraleatnovo, name = "vlraleatnovo"),
    path("vlraleateditar/<uuid:id>", views.vlraleateditar, name = "vlraleateditar"),
    path("respostanovo/<uuid:id>", views.respostanovo, name = "respostanovo"),
    path("respostaeditar/<uuid:id>", views.respostaeditar, name = "respostaeditar"),
    path("textonovo/<uuid:id>", views.textonovo, name = "textonovo"),
    path("textoeditar/<uuid:id>", views.textoeditar, name = "textoeditar"),
    path("anexonovo/<uuid:id>", views.anexonovo, name = "anexonovo"),
    path("anexoeditar/<uuid:id>", views.anexoeditar, name = "anexoeditar"),
    path("apagar/<uuid:id>", views.apagar, name = "apagar"),
    path("programanovo/<uuid:id>", views.programanovo, name = "programanovo"),
    path("programaeditar/<uuid:id>", views.programaeditar, name = "programaeditar"),
    path("propostaeditar/<uuid:id>", views.propostaeditar, name = "propostaeditar"),
    path("proposta/<uuid:id>", views.proposta, name = "proposta"),
    path("testenovo/<uuid:id>", views.testenovo, name = "testenovo"),
    path("testeeditar/<uuid:id>", views.testeeditar, name = "testeeditar"),
]

tarefa/urls.py
from django.urls import path


from . import views

app_name = "tarefa"

urlpatterns = [
    path("avaliacaonovo/<uuid:id>", views.avaliacaonovo, name = "avaliacaonovo"),
    path("avaliacaoeditar/<uuid:id>", views.avaliacaoeditar, name = "avaliacaoeditar"),
    path("questaonovo/<uuid:id>", views.questaonovo, name = "questaonovo"),
    path("questaoeditar/<uuid:id>", views.questaoeditar, name = "questaoeditar"),
    path("relatoriocorrigir1/<uuid:id>", views.relatoriocorrigir1, name = "relatoriocorrigir1"),
    path("relatoriocorrigir2/", views.relatoriocorrigir2, name = "relatoriocorrigir2"),
    path("anexocorrigir1/<uuid:id>", views.anexocorrigir1, name = "anexocorrigir1"),
    path("anexocorrigir2/", views.anexocorrigir2, name = "anexocorrigir2"),
    path("aplicadaeditar/<uuid:id>", views.aplicadaeditar, name = "aplicadaeditar"),
    path("aplicadoeditar/<uuid:id>", views.aplicadoeditar, name = "aplicadoeditar"),
    path("avaliacaoaplicar1/<uuid:id>", views.avaliacaoaplicar1, name = "avaliacaoaplicar1"),
    path("avaliacaoaplicar2/<uuid:id>", views.avaliacaoaplicar2, name = "avaliacaoaplicar2"),
    path("relatorio/<uuid:id>", views.relatorio, name = "relatorio"),
    path("apagar/<uuid:id>", views.apagar, name = "apagar"),
    path("algoritmonovo/<uuid:id>", views.algoritmonovo, name = "algoritmonovo"),
    path("algoritmoeditar/<uuid:id>", views.algoritmoeditar, name = "algoritmoeditar"),
    path("codigo/<uuid:id>", views.codigo, name = "codigo"),
    path("codigocorrigir1/<uuid:id>", views.codigocorrigir1, name = "codigocorrigir1"),
    path("codigocorrigir2/", views.codigocorrigir2, name = "codigocorrigir2"),
    path("codigotestar/<uuid:id>", views.codigotestar, name = "codigotestar"),
    path("valoresaleatoriosver/<uuid:id>", views.valoresaleatoriosver, name = "valoresaleatoriosver"),
]

professor/forms.py
# -*- coding: utf8 -*-
from django import forms

from professor.models import Ementa

class EmentaForm(forms.ModelForm):
	class Meta:
		model = Ementa
		fields=['texto',]
		widgets = {
          'texto': forms.Textarea(attrs={'rows':50, 'cols':120}),
        }

professor/views.py
from django.shortcuts import render
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,render_to_response
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse
from datetime import date,timedelta,datetime,timezone
from django.conf import settings

import os

from painel.models import User,Variavel
from professor.models import Ementa
from professor.forms import EmentaForm
from instituicao.models import Conhecimento,Turma
from situacao.models import Indice,Problema

@login_required
def ementa(request):
    usuario = request.user
    turmas=usuario.na_turma.all()
    ementas=[]
    for turma in turmas :
        ementa=Ementa.objects.filter(conhecimento=turma.conhecimento)
        if ementa :
            ementas.append(ementa[0].texto_md)

    context = {'ementas':ementas,}
    return render(request, 'professor/ementa.html', context)

@login_required
def ementaeditar(request,id):
    conhecimento=Conhecimento.objects.get(id=id)
    ementa=Ementa.objects.get(conhecimento=conhecimento)
    if request.method == 'POST':
        form=EmentaForm(request.POST,instance=ementa)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('professor:conhecimento'))
    else:
        form = EmentaForm(instance=ementa)
    context = {'form':form,'id':id,'ementa':ementa.texto_md}
    return render(request, 'professor/ementaeditar.html', context)


@login_required
def acoes(request):
    context = {}
    return render(request, 'professor/acoes.html', context)


@login_required
def conhecimento(request):
    usuario = request.user
    conhecimentos=Conhecimento.objects.filter(usuario=usuario).order_by('-ativo','instituicao__nome','nome')
    context = {'conhecimentos':conhecimentos}
    return render(request, 'professor/conhecimento.html', context)

@login_required
def alunotarefas(request,idturma,idaluno):
    turma=Turma.objects.get(id=idturma)
    aluno=User.objects.get(id=idaluno)
    context = {'turma':turma,'aluno':aluno}
    return render(request, 'professor/alunotarefas.html', context)


@login_required
def indice(request):
    usuario = request.user
    conhecimentos=Conhecimento.objects.filter(usuario=usuario,ativo=True).order_by('-ativo','instituicao__nome','nome')
    indices=Indice.objects.filter(conhecimento__in=conhecimentos)

    context = {'conhecimentos':conhecimentos,'indices':indices}
    return render(request, 'professor/indice.html', context)





@login_required
def notas(request):
    usuario = request.user
    conhecimentos=Conhecimento.objects.filter(usuario=usuario,ativo=True).order_by('-ativo','instituicao__nome','nome')

    notaporaluno=[]
    for conhecimento in conhecimentos:
        for turma in conhecimento.turmas.all():
            for aluno in turma.alunos.all():
                linha=[]
                linha.append(conhecimento.instituicao.nome)
                linha.append(conhecimento.usuario.last_name)
                linha.append(conhecimento.nome)
                linha.append(turma.nome)
                linha.append(aluno.last_name)
                linha.append(aluno.username)
                total=0
                numquestoes=0
                for aplicada in aluno.aplicadas_usuario.all() :
                    if aplicada.ativo and aplicada.questao.ativo and aplicada.questao.problema.ativo and aplicada.questao.avaliacao.ativo and aplicada.questao.avaliacao.turma.id == turma.id :
                        numquestoes += 1
                        total = total + aplicada.questao.avaliacao.nota*aplicada.questao.nota*(aplicada.get_total_solucao()+aplicada.get_total_relatorio()+aplicada.get_total_anexo())
                for aplicado in aluno.aplicados_usuario.all() :
                    if aplicado.ativo and aplicado.algoritmo.ativo and aplicado.algoritmo.programa.ativo and aplicado.algoritmo.avaliacao.ativo and aplicado.algoritmo.avaliacao.turma.id == turma.id :
                        numquestoes += 1
                        total = total + aplicado.algoritmo.avaliacao.nota*aplicado.algoritmo.nota*aplicado.get_total_codigo()
                linha.append(numquestoes)
                linha.append(total)
                notaporaluno.append(linha)
    # # print(notaporaluno)

    context = {'conhecimentos':conhecimentos,'notaporaluno':notaporaluno}
    return render(request, 'professor/notas.html', context)

professor/templates/professor/acoes.html
{%extends 'base.html' %}

{%load static from staticfiles %}

{% block titulo%}
    CAT@::Ações Prof
{%endblock%}
{% block corpo%}

{% include 'cabecalho.html' %}

    {%if user.is_authenticated %}
        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-10 col-md-10">
                Olá {{user.get_cargo_display}} {{user.last_name}}. Hoje é {% now "d-m-Y H:i"%}.
                <small>
                  ( <a href="{% url 'professor:acoes' %}"> Ações </a> |
                   <a href="{% url 'painel:sair' %}"> Sair </a> )
                </small>
                <small> </br>
                  Para qualquer dúvida e suporte entre em contato com: cata.pro.br@gmail.com
                 </small>
                <hr>
            </div>
            </div>
        </div> <!-- /container 2-->

        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-10 col-md-10">
              <a href="{% url 'professor:conhecimento' %}"> <h3>Gerenciar Conhecimentos e Turmas</h3> </a>
              <a href="{% url 'professor:indice' %}"><h3>Gerenciar Índices e Situações</h3> </a>
            </div>
            </div>
        </div> <!-- /container 2-->


    {%else%}
        </br></br>Acesso não permitido. Favor procurar o Professor desta turma.
    {%endif%}

{%endblock%}

professor/templates/professor/conhecimento.html
{%extends 'base.html' %}

{%load static from staticfiles %}

{% block titulo%}
    CAT@::Ações Prof
{%endblock%}
{% block corpo%}

{% include 'cabecalho.html' %}

    {%if user.is_authenticated %}
        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-10 col-md-10">
                Olá {{user.get_cargo_display}} {{user.last_name}}. Hoje é {% now "d-m-Y H:i"%}.
                <small>
                  ( <a href="{% url 'professor:acoes' %}"> Ações </a> |
                   <a href="{% url 'painel:sair' %}"> Sair </a> )                </small>
                <hr>
            </div>
            </div>
        </div> <!-- /container 2-->

        <!-- Gerenciar Conhecimentos e Turmas: -->
        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-10 col-md-10">
                <h3>Gerenciar Conhecimentos e Turmas:</h3>
                Conhecimento/Disciplina/Curso | <a href={% url 'instituicao:conhecimentonovo' %} title='inserir novo Conhecimento/Disciplina/Curso'> <i class='fas fa-plus'></i></a>
                <div class="dtree">
                   <small><a href="javascript: d.openAll();">Expandir tudo</a> | <a href="javascript: d.closeAll();">Contrair tudo</a></small>
                   <script type="text/javascript">
                    d = new dTree('d');
                    d.add(0,-1,'');
                    {% for conhecimento in conhecimentos %}
                        d.add('{{conhecimento.instituicao.id}}','0','{{conhecimento.instituicao.nome}}');
                        // d.add('{{conhecimento.instituicao.id}}_id','0','Instituicao id: {{conhecimento.instituicao.id}}');
                        d.add("{{conhecimento.usuario.id}}","{{conhecimento.instituicao.id}}","{{conhecimento.usuario.last_name}} ");
                        // d.add("{{conhecimento.usuario.id}}_id","{{conhecimento.instituicao.id}}","Usuario id: {{conhecimento.usuario.id}}");
                        d.add("{{conhecimento.id}}","{{conhecimento.usuario.id}}","{{conhecimento.nome}} |  <a href={% url 'instituicao:conhecimentoeditar' conhecimento.id %} title='Editar este Conhecimento/Disciplina/Curso'> <i class='fas fa-pencil-alt'></i></a> | <a href={% url 'professor:ementaeditar' conhecimento.id %} title='Editar ementa deste Conhecimento/Disciplina/Curso'> <i class='fas fa-chalkboard-teacher'></i></a> | <a href={% url 'instituicao:turmanovo' conhecimento.id %} title='nova turma deste Conhecimento/Disciplina/Curso' > <i class='fas fa-plus'></i></a>");
                        // d.add("{{conhecimento.id}}_id","{{conhecimento.id}}","Conhecimento id: {{conhecimento.id}}");
                        d.add("{{conhecimento.id}}_ativo","{{conhecimento.id}}","Ativo: {{conhecimento.ativo}}");
                        d.add("{{conhecimento.id}}_inicio","{{conhecimento.id}}","Inicio: {{conhecimento.inicio|date:'d-m-Y H:i'}}");
                        d.add("{{conhecimento.id}}_fim","{{conhecimento.id}}","Fim: {{conhecimento.fim|date:'d-m-Y H:i'}}");
                        {% for turma in conhecimento.turmas.all %}
                            d.add("{{turma.id}}","{{turma.conhecimento.id}}","{{turma.nome}} <a href={% url 'instituicao:turmaeditar' turma.id %} title='Editar esta turma'> <i class='fas fa-pencil-alt'></i></a> ");
                            // d.add("{{turma.id}}_id","{{turma.id}}","Turma id: {{turma.id}}");
                            {%if turma.ativo %}
                                d.add("{{turma.id}}_ativo","{{turma.id}}","Ativo: {{turma.ativo}}");
                                d.add("{{turma.id}}_inicio","{{turma.id}}","Inicio: {{turma.inicio|date:'d-m-Y H:i'}}");
                                d.add("{{turma.id}}_fim","{{turma.id}}","Fim: {{turma.fim|date:'d-m-Y H:i'}}");
                                d.add("{{turma.id}}_numero","{{turma.id}}","Qde de questões/algoritmos: {{turma.questao}}");
                                d.add("{{turma.id}}_alunos","{{turma.id}}","Alunos (turma.alunos.all.count) <a href={% url 'painel:alunonovo' turma.id %} title='Inserir novos alunos'> <i class='fas fa-plus'></i></a> | <a href={% url 'painel:alunoeditar' turma.id %} title='Editar meus alunos'> <i class='fas fa-pencil-alt'></i></a>");
                                d.add("{{turma.id}}_avaliacoes","{{turma.id}}","Avaliações <a href={% url 'tarefa:avaliacaonovo' turma.id %} title='nova avaliação'> <i class='fas fa-plus'></i></a>");
                                {% for aluno in turma.alunos.all %}
                                    {% if aluno.is_active %}
                                    d.add("{{aluno.id}}_{{turma.id}}","{{turma.id}}_alunos","{{aluno.last_name}} | {{aluno.username}} | <a href={% url 'painel:senhareset' aluno.id %} title='reset senha para este aluno'> <i class='fas fa-key'></i></a> | <a href={% url 'professor:alunotarefas' turma.id aluno.id %} title='ver tarefas deste aluno'> <i class='fas fa-eye'></i></a>");
                                    {% endif %}
                                {% endfor %}
                                {% for avaliacao in turma.avaliacoes.all %}
                                    d.add("{{avaliacao.id}}","{{turma.id}}_avaliacoes","{{avaliacao.nome}} | Fim: {{avaliacao.fim|date:'d-m-Y H:i'}} <a href={% url 'tarefa:avaliacaoeditar' avaliacao.id %} title='Editar esta avaliação'> <i class='fas fa-pencil-alt'></i></a>")
                                    // d.add("{{avaliacao.id}}_id","{{avaliacao.id}}","Avaliacao id: {{avaliacao.id}}");
                                    d.add('{{avaliacao.id}}_ativa','{{avaliacao.id}}','Ativo: {{avaliacao.ativo}}');
                                    d.add("{{avaliacao.id}}_inicio","{{avaliacao.id}}","Inicio: {{avaliacao.inicio|date:'d-m-Y H:i'}}");
                                    d.add("{{avaliacao.id}}_fim","{{avaliacao.id}}","Fim: {{avaliacao.fim|date:'d-m-Y H:i'}}");
                                    d.add("{{avaliacao.id}}_aplicar","{{avaliacao.id}}","Aplicar avaliação <a href={% url 'tarefa:avaliacaoaplicar1' avaliacao.id %} title='Aplicar esta avaliação aos alunos desta turma.'><i class='far fa-thumbs-up'></i></a>");
                                    d.add('{{avaliacao.id}}_privada','{{avaliacao.id}}','Privada: {{avaliacao.privada}}');
                                    d.add('{{avaliacao.id}}_nota','{{avaliacao.id}}','Nota: {{avaliacao.nota}}');
                                    d.add("{{avaliacao.id}}_questoes","{{avaliacao.id}}","Questões e Algoritmos | <a href={% url 'tarefa:algoritmonovo' avaliacao.id %} title='novo algoritmo nesta avaliação'> <i class='fas fa-laptop'></i></a> : <a href={% url 'tarefa:questaonovo' avaliacao.id %}  title='nova questão nesta avaliação'> <i class='fas fa-calculator'></i></a> ");
                                    {% for questao in avaliacao.questoes.all %}
                                        d.add("{{questao.id}}","{{avaliacao.id}}_questoes","Tarefa: {{questao.numero}} | {{questao.problema.referencia}}: {{questao.problema.descricao}}  | <a href={% url 'tarefa:questaoeditar' questao.id %} title='Editar esta questao'> <i class='fas fa-pencil-alt'></i></a> | <a href={% url 'tarefa:anexocorrigir1' questao.id %} title='Corrigir Anexo desta questão para todos os alunos'> <i class='fas fa-check'></i><i class='fas fa-chart-line'></i></a> | <a href={% url 'tarefa:relatoriocorrigir1' questao.id %} title='Corrigir relatório desta questão para todos os alunos'> <i class='fas fa-check'></i><i class='fas fa-book'></i></a> ");
                                        d.add("{{questao.id}}_ativo","{{questao.id}}","Ativo:{{questao.ativo}}");
                                        d.add("{{questao.id}}_valoresaleatorios","{{questao.id}}","Valores aleatórios <a href={% url 'tarefa:valoresaleatoriosver' questao.id %} title='Ver valores aleatórios desta questao'> <i class='fas fa-eye'></i></a>");
                                        d.add("{{questao.id}}_tentativa","{{questao.id}}","Tentativa:{{questao.tentativa}}");
                                        d.add("{{questao.id}}_tempo","{{questao.id}}","Tempo:{{questao.tempo|time:'H:i'}}");
                                        d.add("{{questao.id}}_nota","{{questao.id}}","Nota:{{questao.nota}}");
                                    {% endfor %}
                                    {% for algoritmo in avaliacao.algoritmos.all %}
                                        d.add("{{algoritmo.id}}","{{avaliacao.id}}_questoes","Programa: {{algoritmo.numero}} | {{algoritmo.programa.referencia}}: {{algoritmo.programa.descricao}} | <a href={% url 'tarefa:algoritmoeditar' algoritmo.id %} title='Editar esta algoritmo'> <i class='fas fa-pencil-alt'></i></a> | <a href={% url 'tarefa:codigocorrigir1' algoritmo.id %} title='Corrigir codigo deste algoritmo para todos os alunos'>  <i class='fas fa-check'></i><i class='fas fa-laptop'></i></a> ");
                                        d.add("{{algoritmo.id}}_ativo","{{algoritmo.id}}","Ativo:{{algoritmo.ativo}}");
                                        d.add("{{algoritmo.id}}_tempo","{{algoritmo.id}}","Tempo:{{algoritmo.tempo|time:'H:i'}}");
                                        d.add("{{algoritmo.id}}_nota","{{algoritmo.id}}","Nota:{{algoritmo.nota}}");
                                    {% endfor %}
                                {% endfor %}
                                d.add("{{turma.id}}_notas","{{turma.id}}","Notas <a href={% url 'instituicao:notas' turma.id %} title='Ver as notas desta turma'> <i class='fas fa-eye'></i></a>");
                            {%endif%}
                        {% endfor %}
                    {% endfor %}
                    document.write(d);
                    </script>
                </div>
            </div>
            </div>
        </div> <!-- /container 2-->

    {%else%}
        </br></br>Acesso não permitido. Favor procurar o Professor desta turma.
    {%endif%}

{%endblock%}

professor/templates/professor/ementa.html
{%extends 'base.html' %}

{%load static from staticfiles %}

{% block titulo%}
    CAT@::Painel
{%endblock%}
{% block corpo%}

{% include 'cabecalho.html' %}

    {%if user.is_authenticated %}

    <div class="container-fluid">
        <div class="row">
        <div class="col-sm-10 col-md-10">
            Olá {{user.get_cargo_display}} {{user.last_name}}. Hoje é {% now "d-m-Y H:i"%}.
            <small>
                ( <a href="{% url 'aluno:atuais' %}"> Atuais </a>
                | <a href="{% url 'painel:sair' %}"> Sair </a> )
            </small>

            <hr>
        </div>
        </div>
    </div> <!-- /container 2-->

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-10 col-md-10">
                    {% for ementa in ementas%}
                        {{ementa|safe}}
                        <hr>
                    {% endfor %}
            </div>
        </div>
    </div> <!-- /container -->

    {%else%}
    </br></br>Acesso não permitido. Favor procurar o Professor desta turma.
    {%endif%}

{%endblock%}

professor/templates/professor/ementaeditar.html
{%extends 'base.html' %}

{%load static from staticfiles %}

{% block titulo%}
    CAT@::Ações Prof
{%endblock%}
{% block corpo%}

{% include 'cabecalho.html' %}

    {%if user.is_authenticated %}
        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-10 col-md-10">
                Olá {{user.get_cargo_display}} {{user.last_name}}. Hoje é {% now "d-m-Y H:i"%}.
                <small>
                    ( <a href="{% url 'professor:conhecimento' %}"> Conhecimentos </a> )
                </small>
                <hr>
            </div>
            </div>
        </div> <!-- /container 1-->

        <div class="container-fluid">
            <div class="row">
            <div class="col-sm-10 col-md-10">
                <h3>Editar esta ementa:</h3>
                <small>Uso estilo markdown. Maiores informações <a href="https://python-markdown.github.io/extensions/#officially-supported-extensions" target="_blank"> Fonte1 </a> <a href="https://github.com/mitya57/python-markdown-math" target="_blank"> Fonte2 </a></small>
                <form action="{% url 'professor:ementaeditar' id %}" method="POST" enctype="multipart/form-data">{%csrf_token%}
                  {% include 'formvictor.html' with form=form %}
                    <input type="submit" value="Enviar informações" />
                </form>
                <hr>
            </div>
            </div>
            <div class="row">
            <div class="col-sm-10 col-md-10">
              <h3>Ementa após edição:</h3>
              <hr>
            {{ementa|safe}}
            </div>
            </div>
    </div> <!-- /container 2-->



        {%else%}
            </br></br>Acesso não permitido. Favor procurar o Professor desta turma.
        {%endif%}

    {%endblock%}